FROM postgres:11

# Add examples and lectures
ADD ./examples /app/postgres/examples
ADD ./lectures /app/postgres/lectures

# Add postgres configuration fiile
ADD ./postgresql.conf /etc/postgresql/postgresql.conf
