insert into illnesses (name) values ('Abscess');
insert into illnesses (name) values ('Alzheimer''s disease');
insert into illnesses (name) values ('Anthrax');
insert into illnesses (name) values ('Appendicitis');
insert into illnesses (name) values ('Allergy');
insert into illnesses (name) values ('Arthritis');
insert into illnesses (name) values ('Aseptic meningitis');
insert into illnesses (name) values ('Asthma');
insert into illnesses (name) values ('Astigmatism');
insert into illnesses (name) values ('Atherosclerosis');
insert into illnesses (name) values ('Bacterial meningitis');
insert into illnesses (name) values ('Beriberi');
insert into illnesses (name) values ('Black Death');
insert into illnesses (name) values ('Botulism');
insert into illnesses (name) values ('Breast cancer');
insert into illnesses (name) values ('Bronchitis');
insert into illnesses (name) values ('Brucellosis');
insert into illnesses (name) values ('Bubonic plague');
insert into illnesses (name) values ('Bunion');
insert into illnesses (name) values ('Boil');
insert into illnesses (name) values ('Campylobacter infection');
insert into illnesses (name) values ('Cancer');
insert into illnesses (name) values ('Candidiasis');
insert into illnesses (name) values ('Carbon monoxide poisoning');
insert into illnesses (name) values ('Coeliac disease');
insert into illnesses (name) values ('Cerebral palsy');
insert into illnesses (name) values ('Chagas disease');
insert into illnesses (name) values ('Chickenpox');
insert into illnesses (name) values ('Chlamydia');
insert into illnesses (name) values ('Chlamydia trachomatis');
insert into illnesses (name) values ('Cholera');
insert into illnesses (name) values ('Chordoma');
insert into illnesses (name) values ('Chorea');
insert into illnesses (name) values ('Chronic fatigue syndrome');
insert into illnesses (name) values ('Circadian rhythm sleep disorder');
insert into illnesses (name) values ('Colitis');
insert into illnesses (name) values ('Common cold');
insert into illnesses (name) values ('Condyloma');
insert into illnesses (name) values ('Congestive heart disease');
insert into illnesses (name) values ('Coronary heart disease');
insert into illnesses (name) values ('Cowpox');
insert into illnesses (name) values ('Crohn''s Disease');
insert into illnesses (name) values ('Dengue Fever');
insert into illnesses (name) values ('Diabetes mellitus');
insert into illnesses (name) values ('Diphtheria');
insert into illnesses (name) values ('Dehydration');
insert into illnesses (name) values ('Dysentery');
insert into illnesses (name) values ('Ear infection');
insert into illnesses (name) values ('Ebola');
insert into illnesses (name) values ('Encephalitis');
insert into illnesses (name) values ('Emphysema');
insert into illnesses (name) values ('Epilepsy');
insert into illnesses (name) values ('Erectile dysfunction');
insert into illnesses (name) values ('Fibromyalgia');
insert into illnesses (name) values ('Foodborne illness');
insert into illnesses (name) values ('Gangrene');
insert into illnesses (name) values ('Gastroenteritis');
insert into illnesses (name) values ('Genital herpes');
insert into illnesses (name) values ('GERD');
insert into illnesses (name) values ('Goitre');
insert into illnesses (name) values ('Gonorrhea');
insert into illnesses (name) values ('Heart disease');
insert into illnesses (name) values ('Hepatitis A');
insert into illnesses (name) values ('Hepatitis B');
insert into illnesses (name) values ('Hepatitis C');
insert into illnesses (name) values ('Hepatitis D');
insert into illnesses (name) values ('Hepatitis E');
insert into illnesses (name) values ('Histiocytosis (childhood cancer)');
insert into illnesses (name) values ('HIV');
insert into illnesses (name) values ('Human papillomavirus');
insert into illnesses (name) values ('Huntington''s disease');
insert into illnesses (name) values ('Hypermetropia');
insert into illnesses (name) values ('Hyperopia');
insert into illnesses (name) values ('Hyperthyroidism');
insert into illnesses (name) values ('Hypothyroid');
insert into illnesses (name) values ('Hypotonia');
insert into illnesses (name) values ('Impetigo');
insert into illnesses (name) values ('Infertility');
insert into illnesses (name) values ('Influenza');
insert into illnesses (name) values ('Interstitial cystitis');
insert into illnesses (name) values ('Iritis');
insert into illnesses (name) values ('Iron-deficiency anemia');
insert into illnesses (name) values ('Irritable bowel syndrome');
insert into illnesses (name) values ('Ignious Syndrome');
insert into illnesses (name) values ('Jaundice');
insert into illnesses (name) values ('Keloids');
insert into illnesses (name) values ('Kuru');
insert into illnesses (name) values ('Kwashiorkor');
insert into illnesses (name) values ('Kidney stone disease');
insert into illnesses (name) values ('Laryngitis');
insert into illnesses (name) values ('Lead poisoning');
insert into illnesses (name) values ('Legionellosis');
insert into illnesses (name) values ('Leishmaniasis');
insert into illnesses (name) values ('Leprosy');
insert into illnesses (name) values ('Leptospirosis');
insert into illnesses (name) values ('Listeriosis');
insert into illnesses (name) values ('Leukemia');
insert into illnesses (name) values ('Lice');
insert into illnesses (name) values ('Loiasis');
insert into illnesses (name) values ('Lung cancer');
insert into illnesses (name) values ('Lupus erythematosus');
insert into illnesses (name) values ('Lyme disease');
insert into illnesses (name) values ('Lymphogranuloma venereum');
insert into illnesses (name) values ('Lymphoma');
insert into illnesses (name) values ('Limbtoosa');
insert into illnesses (name) values ('Mad cow disease');
insert into illnesses (name) values ('Malaria');
insert into illnesses (name) values ('Marburg fever');
insert into illnesses (name) values ('Measles');
insert into illnesses (name) values ('Melanoma');
insert into illnesses (name) values ('Metastatic cancer');
insert into illnesses (name) values ('Meniere''s disease');
insert into illnesses (name) values ('Meningitis');
insert into illnesses (name) values ('Migraine');
insert into illnesses (name) values ('Mononucleosis');
insert into illnesses (name) values ('Multiple myeloma');
insert into illnesses (name) values ('Multiple sclerosis');
insert into illnesses (name) values ('Mumps');
insert into illnesses (name) values ('Muscular dystrophy');
insert into illnesses (name) values ('Myasthenia gravis');
insert into illnesses (name) values ('Myelitis');
insert into illnesses (name) values ('Myoclonus');
insert into illnesses (name) values ('Myopia');
insert into illnesses (name) values ('Myxedema');
insert into illnesses (name) values ('Morquio Syndrome');
insert into illnesses (name) values ('Mattticular syndrome');
insert into illnesses (name) values ('Mononucleosis');
insert into illnesses (name) values ('Neoplasm');
insert into illnesses (name) values ('Non-gonococcal urethritis');
insert into illnesses (name) values ('Necrotizing Fasciitis');
insert into illnesses (name) values ('Night blindness');
insert into illnesses (name) values ('Obesity');
insert into illnesses (name) values ('Osteoarthritis');
insert into illnesses (name) values ('Osteoporosis');
insert into illnesses (name) values ('Otitis');
insert into illnesses (name) values ('Palindromic rheumatism');
insert into illnesses (name) values ('Paratyphoid fever');
insert into illnesses (name) values ('Parkinson''s disease');
insert into illnesses (name) values ('Pelvic inflammatory disease');
insert into illnesses (name) values ('Peritonitis');
insert into illnesses (name) values ('Periodontal disease');
insert into illnesses (name) values ('Pertussis');
insert into illnesses (name) values ('Phenylketonuria');
insert into illnesses (name) values ('Plague');
insert into illnesses (name) values ('Poliomyelitis');
insert into illnesses (name) values ('Porphyria');
insert into illnesses (name) values ('Progeria');
insert into illnesses (name) values ('Prostatitis');
insert into illnesses (name) values ('Psittacosis');
insert into illnesses (name) values ('Psoriasis');
insert into illnesses (name) values ('Pubic lice');
insert into illnesses (name) values ('Pulmonary embolism');
insert into illnesses (name) values ('Pilia');
insert into illnesses (name) values ('pneumonia');
insert into illnesses (name) values ('Q fever');
insert into illnesses (name) values ('Ques fever');
insert into illnesses (name) values ('Rabies');
insert into illnesses (name) values ('Repetitive strain injury');
insert into illnesses (name) values ('Rheumatic fever');
insert into illnesses (name) values ('Rheumatic heart');
insert into illnesses (name) values ('Rheumatism');
insert into illnesses (name) values ('Rheumatoid arthritis');
insert into illnesses (name) values ('Rickets');
insert into illnesses (name) values ('Rift Valley fever');
insert into illnesses (name) values ('Rocky Mountain spotted fever');
insert into illnesses (name) values ('Rubella');
insert into illnesses (name) values ('Salmonellosis');
insert into illnesses (name) values ('Scabies');
insert into illnesses (name) values ('Scarlet fever');
insert into illnesses (name) values ('Sciatica');
insert into illnesses (name) values ('Scleroderma');
insert into illnesses (name) values ('Scrapie');
insert into illnesses (name) values ('Scurvy');
insert into illnesses (name) values ('Sepsis');
insert into illnesses (name) values ('Septicemia');
insert into illnesses (name) values ('SARS');
insert into illnesses (name) values ('Shigellosis');
insert into illnesses (name) values ('Shin splints');
insert into illnesses (name) values ('Shingles');
insert into illnesses (name) values ('Sickle-cell anemia');
insert into illnesses (name) values ('Siderosis');
insert into illnesses (name) values ('SIDS');
insert into illnesses (name) values ('Silicosis');
insert into illnesses (name) values ('Smallpox');
insert into illnesses (name) values ('Stevens–Johnson syndrome');
insert into illnesses (name) values ('Stomach flu');
insert into illnesses (name) values ('Stomach ulcers');
insert into illnesses (name) values ('Strabismus');
insert into illnesses (name) values ('Strep throat');
insert into illnesses (name) values ('Streptococcal infection');
insert into illnesses (name) values ('Synovitis');
insert into illnesses (name) values ('Syphilis');
insert into illnesses (name) values ('Swine influenza');
insert into illnesses (name) values ('Schizophrenia');
insert into illnesses (name) values ('Taeniasis');
insert into illnesses (name) values ('Tay-Sachs disease');
insert into illnesses (name) values ('Tennis elbow');
insert into illnesses (name) values ('Teratoma');
insert into illnesses (name) values ('Tetanus');
insert into illnesses (name) values ('Thalassaemia');
  insert into illnesses (name) values ('Pluchea carolinensis (Jacq.) G. Don');
  insert into illnesses (name) values ('Polemonium micranthum Benth.');
  insert into illnesses (name) values ('Melicope ovalis (H. St. John) T.G. Hartley & B.C. Stone');
  insert into illnesses (name) values ('Fissidens adianthoides Hedw.');
  insert into illnesses (name) values ('Crataegus phaenopyrum (L. f.) Medik.');
  insert into illnesses (name) values ('Pseudopanax K. Koch');
  insert into illnesses (name) values ('Erigeron serpentinus G.L. Nesom');
  insert into illnesses (name) values ('Synthyris pinnatifida S. Watson');
  insert into illnesses (name) values ('Sphagnum fimbriatum Wilson var. concinnum (Berggr.) Warnst.');
  insert into illnesses (name) values ('Arrhenatherum elatius (L.) P. Beauv. ex J. Presl & C. Presl');
  insert into illnesses (name) values ('Chorizanthe membranacea Benth.');
  insert into illnesses (name) values ('Flacourtia Comm. ex L''Hér.');
  insert into illnesses (name) values ('Ludwigia hyssopifolia (G. Don) Exell apud A.R. Fernandes');
  insert into illnesses (name) values ('Cyrtandra heinrichii H. St. John');
  insert into illnesses (name) values ('Equisetum telmateia Ehrh.');
  insert into illnesses (name) values ('Cheilanthes villosa Davenport ex Maxon');
  insert into illnesses (name) values ('Cedrela P. Br.');
  insert into illnesses (name) values ('Penstemon cyananthus Hook.');
  insert into illnesses (name) values ('Pinzona Mart. & Zucc.');
  insert into illnesses (name) values ('Asplenium ×flagrum W.H. Wagner & D.D. Palmer');
  insert into illnesses (name) values ('Achnatherum parishii (Vasey) Barkworth var. parishii');
  insert into illnesses (name) values ('Eleocharis minima Kunth');
  insert into illnesses (name) values ('Eriogonum ammophilum Reveal');
  insert into illnesses (name) values ('Sphaeralcea fendleri A. Gray');
  insert into illnesses (name) values ('Jacquinia berteroi Spreng.');
  insert into illnesses (name) values ('Carex ×crinitoides Lepage');
  insert into illnesses (name) values ('Eupatorium rotundifolium L. var. ovatum (Bigelow) Torr.');
  insert into illnesses (name) values ('Pyrrocoma carthamoides Hook. var. subsquarrosa (Greene) G. Brown & Keil');
  insert into illnesses (name) values ('Oxalis rugeliana Urb.');
  insert into illnesses (name) values ('Helianthemum canadense (L.) Michx.');
  insert into illnesses (name) values ('Benitoa D.D. Keck');
  insert into illnesses (name) values ('Achnatherum hendersonii (Vasey) Barkworth');
  insert into illnesses (name) values ('Crataegus arborea Beadle');
  insert into illnesses (name) values ('Amphicarpum purshii Kunth');
  insert into illnesses (name) values ('Oxalis incarnata L.');
  insert into illnesses (name) values ('Elymus sajanensis (Nevski) Tzvelev');
  insert into illnesses (name) values ('Saccharum ravennae (L.) L.');
  insert into illnesses (name) values ('Polygala glandulosa Kunth');
  insert into illnesses (name) values ('Spergularia bocconii (Scheele) Foucaud ex Merino');
  insert into illnesses (name) values ('Lupinus longifolius (S. Watson) Abrams');
  insert into illnesses (name) values ('Pterocarpus macrocarpus Kurz');
  insert into illnesses (name) values ('Baptisia albescens Small');
  insert into illnesses (name) values ('Salvia reflexa Hornem.');
  insert into illnesses (name) values ('Cistus salviifolius L.');
  insert into illnesses (name) values ('Prunus alleghaniensis Porter var. davisii (W. Wight) Sarg.');
  insert into illnesses (name) values ('Cyclospermum Lag.');
  insert into illnesses (name) values ('Psora luridella (Tuck.) Fink');
  insert into illnesses (name) values ('Stephanomeria exigua Nutt. ssp. carotifera (Hoover) Gottlieb');
  insert into illnesses (name) values ('Ceanothus megacarpus Nutt.');
  insert into illnesses (name) values ('Brya P. Br.');
  insert into illnesses (name) values ('Cynanchum grisebachianum (Schltr.) Alain');
  insert into illnesses (name) values ('Striga asiatica (L.) Kuntze');
  insert into illnesses (name) values ('Balsamorhiza incana Nutt.');
  insert into illnesses (name) values ('Polygonum segetum Kunth');
  insert into illnesses (name) values ('Cynanchum laeve (Michx.) Pers.');
  insert into illnesses (name) values ('Thaspium trifoliatum (L.) A. Gray');
  insert into illnesses (name) values ('Passiflora ×colvillii Sweet');
  insert into illnesses (name) values ('Mikania stevensiana Britton');
  insert into illnesses (name) values ('Coccocarpia palmicola (Spreng.) Arv. & D.J. Galloway');
  insert into illnesses (name) values ('Poa paludigena Fernald & Wiegand');
  insert into illnesses (name) values ('Asplenium ×gravesii Maxon (pro sp.)');
  insert into illnesses (name) values ('Eragrostis elliottii S. Watson');
  insert into illnesses (name) values ('Duboisia leichhardtii (F. Muell.) F. Muell.');
  insert into illnesses (name) values ('Cordia angustifolia (West ex Willd.) Roem. & Schult.');
  insert into illnesses (name) values ('Hydnophytum Jack.');
  insert into illnesses (name) values ('Chamaesyce albomarginata (Torr. & A. Gray) Small');
  insert into illnesses (name) values ('Odontosoria chinensis (L.) J. Sm.');
  insert into illnesses (name) values ('Rosa arvensis Huds.');
  insert into illnesses (name) values ('Spiraea virginiana Britton');
  insert into illnesses (name) values ('Hesperocyparis goveniana (Gordon) Bartel');
  insert into illnesses (name) values ('Poa douglasii Nees');
  insert into illnesses (name) values ('Plumbago scandens L.');
  insert into illnesses (name) values ('Cenchrus brownii Roem. & Schult.');
  insert into illnesses (name) values ('Eriogonum atrorubens Engelm.');
  insert into illnesses (name) values ('Acarospora thelococcoides (Nyl.) Zahlbr.');
  insert into illnesses (name) values ('Cynanchum monense (Britton) Alain');
  insert into illnesses (name) values ('Astragalus brauntonii Parish');
  insert into illnesses (name) values ('Pedicularis labradorica Wirsing');
  insert into illnesses (name) values ('Bonamia repens (I.M. Johnst.) Austin & Staples');
  insert into illnesses (name) values ('Alpinia Roxb.');
  insert into illnesses (name) values ('Ranunculus eschscholtzii Schltdl. var. trisectus (Eastw.) L.D. Benson');
  insert into illnesses (name) values ('Carphephorus carnosus (Small) C.W. James');
  insert into illnesses (name) values ('Prunus lusitanica L.');
  insert into illnesses (name) values ('Lathyrus glandulosus Broich');
  insert into illnesses (name) values ('Caloplaca discolor (Willey) Fink');
  insert into illnesses (name) values ('Chimaphila menziesii (R. Br. ex D. Don) Spreng.');
  insert into illnesses (name) values ('Trichomanes davallioides Gaudich.');
  insert into illnesses (name) values ('Ranunculus macauleyi A. Gray var. macauleyi');
  insert into illnesses (name) values ('Sagittaria graminea Michx. var. weatherbiana (Fernald) Bogin');
  insert into illnesses (name) values ('Aphanostephus ramosissimus DC. var. ramosissimus');
  insert into illnesses (name) values ('Sphaeralcea pedatifida (A. Gray) A. Gray');
  insert into illnesses (name) values ('Carex tonsa (Fernald) E.P. Bicknell var. tonsa');
  insert into illnesses (name) values ('Medicago truncatula Gaertn.');
  insert into illnesses (name) values ('Thamnolia vermicularis (Sw.) Ach. ex Schaerer');
  insert into illnesses (name) values ('Cyanea glabra (E. Wimm.) H. St. John');
  insert into illnesses (name) values ('Symphyotrichum bahamense (Britton) G.L. Nesom');
  insert into illnesses (name) values ('Potentilla fissa Nutt.');
  insert into illnesses (name) values ('Camptotheca acuminata Decne.');
  insert into illnesses (name) values ('Argythamnia adenophora A. Gray');
  insert into illnesses (name) values ('Sagraea domingensis DC.');
  insert into illnesses (name) values ('Selaginella umbrosa Lem. ex Hieron.');
  insert into illnesses (name) values ('Centaurium glanduliferum (Correll) B.L. Turner');
  insert into illnesses (name) values ('Spartina anglica C.E. Hubbard');
  insert into illnesses (name) values ('Tiarella cordifolia L. var. cordifolia');
  insert into illnesses (name) values ('Mirabilis pudica Barneby');
  insert into illnesses (name) values ('Acrocomia Mart.');
  insert into illnesses (name) values ('Napaea L.');
  insert into illnesses (name) values ('Hemizonia congesta DC. ssp. tracyi Babc. & H.M. Hall');
  insert into illnesses (name) values ('Astragalus nudisiliquus A. Nelson');
  insert into illnesses (name) values ('Paliurus Mill.');
  insert into illnesses (name) values ('Dicerandra frutescens Shinners ssp. modesta R.B. Huck');
  insert into illnesses (name) values ('Salix silicicola Raup');
  insert into illnesses (name) values ('Astragalus newberryi A. Gray var. blyae (Rose ex Rydb.) Barneby');
  insert into illnesses (name) values ('Bactrospora dryina (Ach.) A. Massal.');
  insert into illnesses (name) values ('Elaphoglossum alatum Gaudich. var. parvisquamaeum (Skottsb.) W.R. Anderson & Crosby');
  insert into illnesses (name) values ('Chaenactis santolinoides Greene');
  insert into illnesses (name) values ('Draba mogollonica Greene');
  insert into illnesses (name) values ('Solidago sciaphila Steele');
  insert into illnesses (name) values ('Thelypteris kunthii (Desv.) Morton');
  insert into illnesses (name) values ('Calochortus lyallii Baker');
  insert into illnesses (name) values ('Cladonia didyma (Fée) Vain. var. vulcanica (Zoll. & Moritzi) Vain.');
  insert into illnesses (name) values ('Abutilon palmeri A. Gray');
  insert into illnesses (name) values ('Muhlenbergia torreyi (Kunth) Hitchc. ex Bush');
  insert into illnesses (name) values ('Neomacounia Irel.');
  insert into illnesses (name) values ('Arthothelium sanguineum (Willey) Zahlbr.');
  insert into illnesses (name) values ('Quercus coccinea Münchh. var. coccinea');
  insert into illnesses (name) values ('Treculia Decne. ex Trec.');
  insert into illnesses (name) values ('Erythronium L.');
  insert into illnesses (name) values ('Diploicia A. Massal.');
  insert into illnesses (name) values ('Biatorella rappii Zahlbr.');
  insert into illnesses (name) values ('Taraxacum californicum Munz & I.M. Johnst.');
  insert into illnesses (name) values ('Agoseris apargioides (Less.) Greene var. maritima (Sheldon) Q. Jones ex Cronquist');
  insert into illnesses (name) values ('Asplenium flabellulatum Kunze');
  insert into illnesses (name) values ('Heterotheca sessiliflora (Nutt.) Shinners');
  insert into illnesses (name) values ('Bauhinia galpinii N.E. Br.');
  insert into illnesses (name) values ('Micromitrium megalosporum Austin');
  insert into illnesses (name) values ('Peperomia rockii C. DC.');
  insert into illnesses (name) values ('Gilia angelensis V.E. Grant');
  insert into illnesses (name) values ('Echinochloa crus-pavonis (Kunth) Schult. var. crus-pavonis');
  insert into illnesses (name) values ('Thalictrum dasycarpum Fisch. & Avé-Lall.');
  insert into illnesses (name) values ('Bryocaulon divergens (Ach.) Karnefelt');
  insert into illnesses (name) values ('Metasequoia glyptostroboides Hu & W.C. Cheng');
  insert into illnesses (name) values ('Pseudocryphaea E. Britton ex Broth.');
  insert into illnesses (name) values ('Penstemon australis Small');
  insert into illnesses (name) values ('Verrucaria iovensis Servit');
  insert into illnesses (name) values ('Cyathea cooperi (Hook. ex F. Muell.) Domin');
  insert into illnesses (name) values ('Mangifera altissima Blanco');
  insert into illnesses (name) values ('Arabis furcata S. Watson var. furcata');
  insert into illnesses (name) values ('Schiedea hawaiiensis Hillebr.');
  insert into illnesses (name) values ('Ardisia Sw.');
  insert into illnesses (name) values ('Parthenice A. Gray');
  insert into illnesses (name) values ('Hudsonia tomentosa Nutt. var. tomentosa');
  insert into illnesses (name) values ('Phaseolus filiformis Benth.');
  insert into illnesses (name) values ('Plagiobothrys chorisianus (Cham.) I.M. Johnst. var. chorisianus');
  insert into illnesses (name) values ('Monardella viridis Jeps.');
  insert into illnesses (name) values ('Claytonia megarhiza (A. Gray) Parry ex S. Watson var. megarhiza');
  insert into illnesses (name) values ('Cladoraphis Franch.');
  insert into illnesses (name) values ('Buxbaumia viridis (DC.) Moug. & Nestl.');
  insert into illnesses (name) values ('Townsendia condensata Parry ex A. Gray');
  insert into illnesses (name) values ('Thysanocarpus Hook.');
  insert into illnesses (name) values ('Polypogon maritimus Willd.');
  insert into illnesses (name) values ('Caragana korshinskii Kom.');
  insert into illnesses (name) values ('Setaria setosa (Sw.) P. Beauv. var. setosa');
  insert into illnesses (name) values ('Hypotrachyna showmanii Hale');
  insert into illnesses (name) values ('Abies lasiocarpa (Hook.) Nutt. var. arizonica (Merriam) Lemmon');
  insert into illnesses (name) values ('Triphora amazonica Schltr.');
  insert into illnesses (name) values ('Astragalus tricarinatus A. Gray');
  insert into illnesses (name) values ('Symphyotrichum fendleri (A. Gray) G.L. Nesom');
  insert into illnesses (name) values ('Brodiaea elegans Hoover');
  insert into illnesses (name) values ('Scaevola sericea Vahl var. sericea');
  insert into illnesses (name) values ('Shortia galacifolia Torr. & A. Gray var. brevistyla Davies');
  insert into illnesses (name) values ('Apluda mutica L.');
  insert into illnesses (name) values ('Minuartia howellii (S. Watson) Mattf.');
  insert into illnesses (name) values ('Asimina obovata (Willd.) Nash');
  insert into illnesses (name) values ('Thuidium philibertii Limpr.');
  insert into illnesses (name) values ('Leavenworthia uniflora (Michx.) Britton');
  insert into illnesses (name) values ('Malva moschata L.');
  insert into illnesses (name) values ('Solidago flexicaulis L.');
  insert into illnesses (name) values ('Astragalus anxius R.J. Meinke & Kaye');
  insert into illnesses (name) values ('Usnea strigosa (Ach.) Eaton ssp. major (Michx.) I. Tav.');
  insert into illnesses (name) values ('Begonia foliosa Kunth var. miniata (Planch.) L.B. Sm. & B.G. Schub.');
  insert into illnesses (name) values ('Stipulicida Michx.');
  insert into illnesses (name) values ('Hydrophyllum appendiculatum Michx.');
  insert into illnesses (name) values ('Penstemon purpusii Brandegee');
  insert into illnesses (name) values ('Sidalcea oregana (Nutt. ex Torr. & A. Gray) A. Gray ssp. oregana var. maxima (M. Peck) C.L. Hitchc.');
  insert into illnesses (name) values ('Carex bolanderi Olney');
  insert into illnesses (name) values ('Melaleuca ericifolia Sm.');
  insert into illnesses (name) values ('Chorizanthe xanti S. Watson var. xanti');
  insert into illnesses (name) values ('Leucolepis Lindb.');
  insert into illnesses (name) values ('Silene repens Patrin ex Pers. ssp. purpurata (Greene) C.L. Hitchc. & Maguire');
  insert into illnesses (name) values ('Guatteria Ruiz & Pav.');
  insert into illnesses (name) values ('Honckenya peploides (L.) Ehrh. ssp. peploides (L.) Ehrh. [excluded]');
  insert into illnesses (name) values ('Iris orientalis Mill.');
  insert into illnesses (name) values ('Cynodon aethiopicus W.D. Clayton & Harlan');
  insert into illnesses (name) values ('Phacelia nemoralis Greene ssp. oregonensis Heckard');
  insert into illnesses (name) values ('Echinocereus pentalophus (DC.) Lem.');
  insert into illnesses (name) values ('Calystegia spithamaea (L.) Pursh ssp. stans (Michx.) Brummitt');
  insert into illnesses (name) values ('Astragalus nuttallianus DC.');
  insert into illnesses (name) values ('Psychilis monensis Sauleda');
  insert into illnesses (name) values ('Anthracothecium subglobosum Riddle');
  insert into illnesses (name) values ('Psoralidium tenuiflorum (Pursh) Rydb.');
  insert into illnesses (name) values ('Helianthemum nashii Britton');
  insert into illnesses (name) values ('Polygonella Michx.');
  insert into illnesses (name) values ('Adenophyllum cooperi (A. Gray) Strother');
  insert into illnesses (name) values ('Tofieldia Huds.');
  insert into illnesses (name) values ('Phlox glabriflora (Brand) Whitehouse');
  insert into illnesses (name) values ('Cladonia grayi G. Merr. ex Sandst.');
  insert into illnesses (name) values ('Halimolobos diffusa (A. Gray) O.E. Schulz');
  insert into illnesses (name) values ('Cyanea spathulata (Hillebr.) A. Heller');
  insert into illnesses (name) values ('Cleome viscosa L.');
  insert into illnesses (name) values ('Eulophia alta (L.) Fawc. & Rendle');
  insert into illnesses (name) values ('Usnea merrillii Mot.');
  insert into illnesses (name) values ('Phlox pilosa L. ssp. riparia Wherry');
  insert into illnesses (name) values ('Placynthium asperellum (Ach.) Trevis.');
  insert into illnesses (name) values ('Matthiola longipetala (Vent.) DC.');
  insert into illnesses (name) values ('Oncosiphon suffruticosum (L.) Källersjö');
  insert into illnesses (name) values ('Draba asterophora Payson');
  insert into illnesses (name) values ('Ipomopsis tenuituba (Rydb.) V.E. Grant ssp. latiloba V.E. Grant & Wilken');
  insert into illnesses (name) values ('Carlowrightia linearifolia (Torr.) A. Gray');
  insert into illnesses (name) values ('Sarracenia leucophylla Raf.');
  insert into illnesses (name) values ('Paspalum hartwegianum Fourn.');
  insert into illnesses (name) values ('Geum canadense Jacq. var. canadense');
  insert into illnesses (name) values ('Lecidea subplebeja Vain.');
  insert into illnesses (name) values ('Astragalus wingatanus S. Watson');
  insert into illnesses (name) values ('Convolvulus nodiflorus Desv.');
  insert into illnesses (name) values ('Hibiscus tiliaceus L.');
  insert into illnesses (name) values ('Xylosma crenata (H. St. John) H. St. John');
  insert into illnesses (name) values ('Rochefortia acanthophora (DC.) Griseb.');
  insert into illnesses (name) values ('Mitella diphylla L.');
  insert into illnesses (name) values ('Pinus caribaea Morelet');
  insert into illnesses (name) values ('Thelypteris noveboracensis (L.) Nieuwl.');
  insert into illnesses (name) values ('Silene hookeri Nutt.');
  insert into illnesses (name) values ('Xyris panacea L.C. Anderson & Kral');
  insert into illnesses (name) values ('Eucalyptus crebra F. Muell.');
  insert into illnesses (name) values ('Crataegus phippsii R. O''Kennon');
  insert into illnesses (name) values ('Rosa stellata Wooton ssp. stellata');
  insert into illnesses (name) values ('Lellingeria suspensa (L.) A.R. Sm. & R.C. Moran');
  insert into illnesses (name) values ('Cladonia cristatella Tuck.');
  insert into illnesses (name) values ('Ditrichum schimperi (Lesq.) Kuntze');
  insert into illnesses (name) values ('Juncus effusus L. var. conglomeratus (L.) Engelm.');
  insert into illnesses (name) values ('Erigeron arisolius G.L. Nesom');
  insert into illnesses (name) values ('Parmelia Ach.');
  insert into illnesses (name) values ('Crataegus coleae Sarg.');
  insert into illnesses (name) values ('Delphinium carolinianum Walter ssp. carolinianum');
  insert into illnesses (name) values ('Erigeron philadelphicus L.');
  insert into illnesses (name) values ('Commelina tuberosa L.');
  insert into illnesses (name) values ('Centaurea virgata Lam.');
  insert into illnesses (name) values ('Euphorbia resinifera Berg');
  insert into illnesses (name) values ('Picrasma excelsa (Sw.) Planch.');
  insert into illnesses (name) values ('Pistacia terebinthus L.');
  insert into illnesses (name) values ('Romneya Harv.');
  insert into illnesses (name) values ('Peltigera polydactylon (Neck.) Hoffm.');
  insert into illnesses (name) values ('Coptis laciniata A. Gray');
  insert into illnesses (name) values ('Salix athabascensis Raup');
  insert into illnesses (name) values ('Physaria geyeri (Hook.) A. Gray var. purpurea Rollins');
  insert into illnesses (name) values ('Solanum lanceifolium Jacq.');
  insert into illnesses (name) values ('Cirsium scariosum Nutt.');
  insert into illnesses (name) values ('Salicornia depressa Standl.');
  insert into illnesses (name) values ('Smelowskia borealis (Greene) Drury & Rollins var. villosa Drury & Rollins');
  insert into illnesses (name) values ('Polypodium triseriale Sw.');
  insert into illnesses (name) values ('Sporobolus vaginiflorus (Torr. ex A. Gray) Alph. Wood var. vaginiflorus');
  insert into illnesses (name) values ('Silene cryptopetala Hillebr.');
  insert into illnesses (name) values ('Oligoneuron riddellii (Frank ex Riddell) Rydb.');
  insert into illnesses (name) values ('Thelypteris cordata (Fée) Proctor var. imitata (C. Chr.) Proctor');
  insert into illnesses (name) values ('Lyrocarpa coulteri Hook. & Harv. ex Harv. var. palmeri (S. Watson) Rollins');
  insert into illnesses (name) values ('Lantana canescens Kunth');
  insert into illnesses (name) values ('Cymbalaria muralis G. Gaertn., B. Mey. & Scherb.');
  insert into illnesses (name) values ('Schiedea kaalae Wawra');
  insert into illnesses (name) values ('Evernia mesomorpha Nyl.');
  insert into illnesses (name) values ('Potentilla concinna Richardson var. proxima (Rydb.) S.L. Welsh & B.C. Johnst.');
  insert into illnesses (name) values ('Sarcogyne clavus (DC.) Krempelh.');
  insert into illnesses (name) values ('Hypericum fasciculatum Lam.');
  insert into illnesses (name) values ('Androsace chamaejasme Wulfen ssp. carinata (Torr.) Hultén');
  insert into illnesses (name) values ('Cheirodendron Nutt. ex Seem.');
  insert into illnesses (name) values ('Platystemon Benth.');
  insert into illnesses (name) values ('Acarospora canadensis H. Magn.');
  insert into illnesses (name) values ('Chrysopsis gossypina (Michx.) Elliott ssp. cruiseana (Dress) Semple');
  insert into illnesses (name) values ('Carex platyphylla Carey');
  insert into illnesses (name) values ('Basiphyllaea Schltr.');
  insert into illnesses (name) values ('Sesuvium portulacastrum (L.) L. var. portulacastrum ');
  insert into illnesses (name) values ('Lantana velutina M. Martens & Galeotti');
  insert into illnesses (name) values ('Ononis alopecuroides L.');
  insert into illnesses (name) values ('Arenaria kingii (S. Watson) M.E. Jones ssp. compacta (Coville) Maguire');
  insert into illnesses (name) values ('Lilium rubescens S. Watson');
  insert into illnesses (name) values ('Veratrum hybridum (Walter) J.H. Zimmerman ex Zomlefer');
  insert into illnesses (name) values ('Stereophyllum Mitt.');
  insert into illnesses (name) values ('Claytonia arenicola L.F. Hend.');
  insert into illnesses (name) values ('Ambrosia ambrosioides (Cav.) Payne');
  insert into illnesses (name) values ('Senecio cannabinifolius Hook. & Arn.');
  insert into illnesses (name) values ('Tilia platyphyllos Scop.');
  insert into illnesses (name) values ('Poa wheeleri Vasey');
  insert into illnesses (name) values ('Chrysoma pauciflosculosa (Michx.) Greene');
  insert into illnesses (name) values ('Thelesperma subnudum A. Gray');
  insert into illnesses (name) values ('Ageratina lemmonii (B.L. Rob.) R.M. King & H. Rob.');
  insert into illnesses (name) values ('Echinochloa pyramidalis (Lam.) Hitchc. & Chase');
  insert into illnesses (name) values ('Lasthenia chrysantha (Greene ex A. Gray) Greene');
  insert into illnesses (name) values ('Portulaca umbraticola Kunth ssp. coronata (Small) Matthews & Ketron');
  insert into illnesses (name) values ('Chloris elata Desv.');
  insert into illnesses (name) values ('Ajuga pyramidalis L.');
  insert into illnesses (name) values ('Gentianella wrightii (A. Gray) Holub');
  insert into illnesses (name) values ('Digitaria longiflora (Retz.) Pers.');
  insert into illnesses (name) values ('Rhodiola rhodantha (A. Gray) H. Jacobsen');
  insert into illnesses (name) values ('Arachis hypogaea L.');
  insert into illnesses (name) values ('Polystichum acrostichoides (Michx.) Schott var. acrostichoides');
  insert into illnesses (name) values ('Crataegus munda Beadle');
  insert into illnesses (name) values ('Fabronia ciliaris (Brid.) Brid. var. wrightii (Sull.) W.R. Buck');
  insert into illnesses (name) values ('Selenia jonesii Cory var. jonesii');
  insert into illnesses (name) values ('Peucedanum sandwicense Hillebr.');
  insert into illnesses (name) values ('Nicolletia occidentalis A. Gray');
  insert into illnesses (name) values ('Bryum reedii H. Rob.');
  insert into illnesses (name) values ('Pterygiopsis Vain.');
  insert into illnesses (name) values ('Dracunculus Mill.');
  insert into illnesses (name) values ('Gastridium phleoides (Nees & Meyen) C.E. Hubbard');
  insert into illnesses (name) values ('Claytonia tuberosa Pall. ex Schult. var. czukczorum (Volkova) Hultén');
  insert into illnesses (name) values ('Abronia neurophylla Standl.');
  insert into illnesses (name) values ('Pisonia capitata (S. Watson) Standl.');
  insert into illnesses (name) values ('Monardella odoratissima Benth.');
  insert into illnesses (name) values ('Psychotria greenwelliae Fosberg');
  insert into illnesses (name) values ('Lonicera involucrata (Richardson) Banks ex Spreng.');
  insert into illnesses (name) values ('Selaginella ludoviciana A. Braun');
  insert into illnesses (name) values ('Fraxinus mandshurica Rupr.');
  insert into illnesses (name) values ('Lecanora microbola H. Magn.');
  insert into illnesses (name) values ('Nama californicum (A. Gray) Bacon');
  insert into illnesses (name) values ('Eriogonum lancifolium Reveal & Brotherson');
  insert into illnesses (name) values ('Couroupita guianensis Aubl.');
  insert into illnesses (name) values ('Synthlipsis greggii A. Gray');
  insert into illnesses (name) values ('Pyrenocollema caesium (Nyl.) R.C. Harris');
  insert into illnesses (name) values ('Scutellaria floridana Chapm.');
  insert into illnesses (name) values ('Achillea ptarmica L.');
  insert into illnesses (name) values ('Massalongia microphylliza (Nyl. ex Hasse) Henssen');
  insert into illnesses (name) values ('Blennosperma bakeri Heiser');
  insert into illnesses (name) values ('Paronychia canadensis (L.) Alph. Wood');
  insert into illnesses (name) values ('Juncus secundus P. Beauv. ex Poir.');
  insert into illnesses (name) values ('Chamaesyce dioica (Kunth) Millsp.');
  insert into illnesses (name) values ('Pogogyne Benth.');
  insert into illnesses (name) values ('Entodon concinnus (De Not.) Par.');
  insert into illnesses (name) values ('Penstemon ammophilus N.H. Holmgren & L.M. Shultz');
  insert into illnesses (name) values ('Impatiens balfourii Hook. f.');
  insert into illnesses (name) values ('Nemophila menziesii Hook. & Arn. var. integrifolia Parish');
  insert into illnesses (name) values ('Oenothera fruticosa L. ssp. fruticosa');
  insert into illnesses (name) values ('Achillea filipendulina Lam.');
  insert into illnesses (name) values ('Phyllanthus tenellus Roxb.');
  insert into illnesses (name) values ('Picradeniopsis Rydb. ex Britton');
  insert into illnesses (name) values ('Calochortus clavatus S. Watson var. recurvifolius (Hoover) R. Fiedler & P. Zebell');
  insert into illnesses (name) values ('Cistanthe parryi (A. Gray) Hershkovitz var. hesseae (J.H. Thomas) Kartesz & Gandhi');
  insert into illnesses (name) values ('Emex australis Steinh.');
  insert into illnesses (name) values ('Cyperus echinatus (L.) Alph. Wood');
  insert into illnesses (name) values ('Conocarpus L.');
  insert into illnesses (name) values ('Lecanora nordenskioeldii Vain.');
  insert into illnesses (name) values ('Epimedium L.');
  insert into illnesses (name) values ('Astragalus malacus A. Gray');
  insert into illnesses (name) values ('Chenopodium rubrum L.');
  insert into illnesses (name) values ('Condalia ericoides (A. Gray) M.C. Johnst.');
  insert into illnesses (name) values ('Monarda russeliana Nutt. ex Sims');
  insert into illnesses (name) values ('Draba oreibata J.F. Macbr. & Payson ex Payson var. oreibata');
  insert into illnesses (name) values ('Crumia latifolia (Kindb.) Schof.');
  insert into illnesses (name) values ('Plectranthus barbatus Andrews');
  insert into illnesses (name) values ('Ericameria palmeri (A. Gray) H.M. Hall');
  insert into illnesses (name) values ('Leptogium juniperinum Tuck.');
  insert into illnesses (name) values ('Eriogonum crosbyae Reveal');
  insert into illnesses (name) values ('Castilleja occidentalis Torr.');
  insert into illnesses (name) values ('Chaenomeles ×superba (Frahm) Rehder');
  insert into illnesses (name) values ('Saussurea americana D.C. Eaton');
  insert into illnesses (name) values ('Euphorbia esula L. var. uralensis (Fisch. ex Link) Dorn');
  insert into illnesses (name) values ('Lecanora subintricata (Nyl.) Th. Fr.');
  insert into illnesses (name) values ('Cypripedium montanum Douglas ex Lindl.');
  insert into illnesses (name) values ('Blighia sapida K.D. Koenig');
  insert into illnesses (name) values ('Corydalis scouleri Hook.');
  insert into illnesses (name) values ('Stenaria nigricans (Lam.) Terrell var. floridana (Standl.) Terrell');
  insert into illnesses (name) values ('Veronica alpina L.');
  insert into illnesses (name) values ('Cuscuta brachycalyx (Yunck.) Yunck.');
  insert into illnesses (name) values ('Lithospermum ruderale Douglas ex Lehm.');
  insert into illnesses (name) values ('Salvia potus Epling');
  insert into illnesses (name) values ('Mycoglaena meridionalis (Zahlbr.) Szat.');
  insert into illnesses (name) values ('Hillebrandia Oliv.');
  insert into illnesses (name) values ('Lactuca graminifolia Michx.');
  insert into illnesses (name) values ('Trypethelium tropicum (Ach.) Müll. Arg.');
  insert into illnesses (name) values ('Aquilegia chrysantha A. Gray var. chaplinei (Standl. ex Payson) Lott');
  insert into illnesses (name) values ('Viola ×malteana House');
  insert into illnesses (name) values ('Pseudognaphalium sandwicensium (Gaudich.) Anderb. var. kilaueanum (O. Deg. & Sherff) W.L. Wagner');
  insert into illnesses (name) values ('Cyanea procera Hillebr.');
  insert into illnesses (name) values ('Frangula alnus Mill.');
  insert into illnesses (name) values ('Proboscidea Schmidel');
  insert into illnesses (name) values ('Platanthera ×bicolor (Raf.) Luer (pro sp.)');
  insert into illnesses (name) values ('Porotrichum vancouveriense (Kindb.) H.A. Crum');
  insert into illnesses (name) values ('Carex socialis Mohlenbr. & Schwegm.');
  insert into illnesses (name) values ('Bromus biebersteinii Roem. & Schult. [excluded]');
  insert into illnesses (name) values ('Honckenya peploides (L.) Ehrh.');
  insert into illnesses (name) values ('Eriastrum densifolium (Benth.) H. Mason ssp. sanctorum (Milliken) H. Mason');
  insert into illnesses (name) values ('Caryota urens L.');
  insert into illnesses (name) values ('Galeopsis tetrahit L.');
  insert into illnesses (name) values ('Juglans microcarpa Berl.');
  insert into illnesses (name) values ('Centromadia parryi (Greene) Greene ssp. parryi');
  insert into illnesses (name) values ('Eustachys paspaloides (Vahl) Lanza & Mattei ssp. caribaea (Spreng.) Nowack');
  insert into illnesses (name) values ('Actaea rubra (Aiton) Willd.');
  insert into illnesses (name) values ('Cordyla Lour.');
  insert into illnesses (name) values ('Milium effusum L.');
  insert into illnesses (name) values ('Echinacea purpurea (L.) Moench');
  insert into illnesses (name) values ('Plagiothecium cavifolium (Brid.) Z. Iwats.');
  insert into illnesses (name) values ('Carex hitchcockiana Dewey');
  insert into illnesses (name) values ('Rhizocarpon oederi (Weber) Körb.');
  insert into illnesses (name) values ('Poa cusickii Vasey');
  insert into illnesses (name) values ('Hedyotis schlechtendahliana Steud.');
  insert into illnesses (name) values ('Sairocarpus kingii (S. Watson) D.A. Sutton');
  insert into illnesses (name) values ('Bacidia polychroa (Th. Fr.) Körb.');
  insert into illnesses (name) values ('Centratherum punctatum Cass.');
  insert into illnesses (name) values ('Chelidonium L.');
  insert into illnesses (name) values ('Saponaria officinalis L.');
  insert into illnesses (name) values ('Astragalus sabulosus M.E. Jones var. vehiculus S.L. Welsh');
  insert into illnesses (name) values ('Rosa nutkana C. Presl');
  insert into illnesses (name) values ('Vernonia blodgettii Small');
  insert into illnesses (name) values ('Spiranthes vernalis Engelm. & A. Gray');
  insert into illnesses (name) values ('Dorema ammoniacum D. Don');
  insert into illnesses (name) values ('Graphis intricata Fée');
  insert into illnesses (name) values ('Rubus lawrencei L.H. Bailey');
  insert into illnesses (name) values ('Impatiens aurella Rydb.');
  insert into illnesses (name) values ('Prosopis laevigata (Humb. & Bonpl. ex Willd.) M.C. Johnst.');
  insert into illnesses (name) values ('Monolepis pusilla Torr. ex S. Watson');
  insert into illnesses (name) values ('Crataegus pinetorum Beadle');
  insert into illnesses (name) values ('Peumus boldus Molina');
  insert into illnesses (name) values ('Carex occidentalis L.H. Bailey');
  insert into illnesses (name) values ('Lonicera caerulea L.');
  insert into illnesses (name) values ('Engelmannia A. Gray ex Nutt.');
  insert into illnesses (name) values ('Briza humilis M. Bieb.');
  insert into illnesses (name) values ('Trachyxiphium heteroicum (Cardot) W.R. Buck');
  insert into illnesses (name) values ('Loiseleuria Desv.');
  insert into illnesses (name) values ('Escobaria sandbergii Castetter, Pierce & Schwerin');
  insert into illnesses (name) values ('Vitis rotundifolia Michx. var. rotundifolia');
  insert into illnesses (name) values ('Heterotheca oregona (Nutt.) Shinners');
  insert into illnesses (name) values ('Aralia californica S. Watson');
  insert into illnesses (name) values ('Phyllostegia bracteata Sherff');
  insert into illnesses (name) values ('Pelargonium panduriforme Eckl. & Zeyh.');
  insert into illnesses (name) values ('Arctostaphylos purissima P.V. Wells');
  insert into illnesses (name) values ('Eriogonum luteolum Greene');
  insert into illnesses (name) values ('Emilia Cass.');
  insert into illnesses (name) values ('Dyschoriste schiedeana (Nees) Kuntze var. cinerascens Henrickson & Hilsenb.');
  insert into illnesses (name) values ('Arabis lemmonii S. Watson var. drepanoloba (Greene) Rollins');
  insert into illnesses (name) values ('Carex scirpoidea Michx. ssp. scirpoidea');
  insert into illnesses (name) values ('Cryptantha albida (Kunth) I.M. Johnst.');
  insert into illnesses (name) values ('Mycoblastus marginatus Degel.');
  insert into illnesses (name) values ('Solorina spongiosa (Ach.) Anzi');
  insert into illnesses (name) values ('Rubus arenicola Blanch.');
  insert into illnesses (name) values ('Poa cusickii Vasey ssp. purpurascens (Vasey) Soreng');
  insert into illnesses (name) values ('Orthodontium Schwägr.');
  insert into illnesses (name) values ('Phacelia rotundifolia Torr. ex S. Watson');
  insert into illnesses (name) values ('Sorbus groenlandica (C.K. Schneid.) Á. Löve & D. Löve');
  insert into illnesses (name) values ('Collinsia callosa Parish');
  insert into illnesses (name) values ('Podranea ricasoliana (Tanfani) Sprague');
  insert into illnesses (name) values ('Scolosanthus Vahl');
  insert into illnesses (name) values ('Hymenothrix wislizeni A. Gray');
  insert into illnesses (name) values ('Anoda crenatiflora Ortega');
  insert into illnesses (name) values ('Oenothera deltoides Torr. & Frém. ssp. howellii (Munz) W. Klein');
  insert into illnesses (name) values ('Sericocarpus rigidus Lindl.');
  insert into illnesses (name) values ('Sarracenia flava L.');
  insert into illnesses (name) values ('Mielichhoferia tehamensis Showers');
  insert into illnesses (name) values ('Monardella nana A. Gray ssp. arida (H.M. Hall) Abrams');
  insert into illnesses (name) values ('Potentilla norvegica L. ssp. monspeliensis (L.) Asch. & Graebn.');
  insert into illnesses (name) values ('Dichanthelium sabulorum (Lam.) Gould & C.A. Clark');
  insert into illnesses (name) values ('Microsorum spectrum (Kaulf.) Copeland');
  insert into illnesses (name) values ('Monardella odoratissima Benth.');
  insert into illnesses (name) values ('Encalypta affinis R. Hedw. var. macounii (Austin) H.A. Crum & L.E. Anderson');
  insert into illnesses (name) values ('Dichodontium olympicum Renauld & Cardot');
  insert into illnesses (name) values ('Delphinium ×burkei Greene (pro sp.)');
  insert into illnesses (name) values ('Hieracium ×brachiatum Bethel. ex DC.');
  insert into illnesses (name) values ('Eutrema R. Br.');
  insert into illnesses (name) values ('Lespedeza thunbergii (DC.) Nakai');
  insert into illnesses (name) values ('Eriogonum umbellatum Torr. var. aureum (Gandog.) Reveal');
  insert into illnesses (name) values ('Dyschoriste schiedeana (Nees) Kuntze var. cinerascens Henrickson & Hilsenb.');
  insert into illnesses (name) values ('Chaenotheca chrysocephala (Turner ex Ach.) Th. Fr.');
  insert into illnesses (name) values ('Patis racemosa (Sm.) Romasch., P.M. Peterson & R. J. Soreng');
  insert into illnesses (name) values ('Wigandia urens (Ruiz & Pav.) Kunth var. caracasana (Kunth) D. Gibson');
  insert into illnesses (name) values ('Chamaesyce geyeri (Engelm. & A. Gray) Small var. wheeleriana (Warnock & M.C. Johnst.) Mayfield');
  insert into illnesses (name) values ('Meximalva filipes (A. Gray) Fryxell');
  insert into illnesses (name) values ('Tortula bolanderi (Lesq.) Howe');
  insert into illnesses (name) values ('Lobaria pseudopulmonaria Gyel.');
  insert into illnesses (name) values ('Monolopia stricta Crum');
  insert into illnesses (name) values ('Euphrasia micrantha Rchb.');
  insert into illnesses (name) values ('Lotus crassifolius (Benth.) Greene var. otayensis Moran ex Isely');
  insert into illnesses (name) values ('Cestrum aurantiacum Lindl.');
  insert into illnesses (name) values ('Schoenoplectus pungens (Vahl) Palla var. longispicatus (Britton) S.G. Sm.');
  insert into illnesses (name) values ('Rubus permixtus Blanch.');
  insert into illnesses (name) values ('Melanelia panniformis (Nyl.) Essl.');
  insert into illnesses (name) values ('Ramalina stenospora Müll. Arg.');
  insert into illnesses (name) values ('Draba oreibata J.F. Macbr. & Payson ex Payson var. serpentina Tiehm & P.K. Holmgren');
  insert into illnesses (name) values ('Eucalyptus macrandra F. Muell. ex Benth.');
  insert into illnesses (name) values ('Dodonaea viscosa (L.) Jacq.');
  insert into illnesses (name) values ('Anisacanthus linearis (Hagen) Henrickson & Lott');
  insert into illnesses (name) values ('Gilia aliquanta A.D. Grant & V.E. Grant ssp. aliquanta');
  insert into illnesses (name) values ('Pannaria hookeri (Borrer ex Sm.) Nyl.');
  insert into illnesses (name) values ('Carex teneriformis Mack.');
  insert into illnesses (name) values ('Lessingia nemaclada Greene var. mendocina (Greene) J.T. Howell');
  insert into illnesses (name) values ('Cladidium Hafellner');
  insert into illnesses (name) values ('Matelea baldwyniana (Sweet) Woodson');
  insert into illnesses (name) values ('Waltheria indica L.');
  insert into illnesses (name) values ('Marrubium L.');
  insert into illnesses (name) values ('Boerhavia triquetra S. Watson');
  insert into illnesses (name) values ('Lomatium utriculatum (Nutt. ex Torr. & A. Gray) J.M. Coult. & Rose');
  insert into illnesses (name) values ('Potentilla subjuga Rydb.');
  insert into illnesses (name) values ('Muhlenbergia utilis (Torr.) Hitchc.');
  insert into illnesses (name) values ('Trisetum sibiricum Rupr.');
  insert into illnesses (name) values ('Ipomoea quamoclit L.');
  insert into illnesses (name) values ('Astragalus eurekensis M.E. Jones');
  insert into illnesses (name) values ('Alyssum obovatum (C.A. Mey.) Turcz.');
  insert into illnesses (name) values ('Melicope degeneri (B.C. Stone) T.G. Hartley & B.C. Stone');
  insert into illnesses (name) values ('Senecio lyonii A. Gray');
  insert into illnesses (name) values ('Tetracoccus ilicifolius Coville & Gilman');
  insert into illnesses (name) values ('Ludwigia glandulosa Walter ssp. brachycarpa (Torr. & A. Gray) Peng');
  insert into illnesses (name) values ('Calystegia malacophylla (Greene) Munz ssp. malacophylla var. malacophylla');
  insert into illnesses (name) values ('Cuphea procumbens Ortega');
  insert into illnesses (name) values ('Plagiobothrys torreyi (A. Gray) A. Gray var. torreyi');
  insert into illnesses (name) values ('Cyathea borinquena (Maxon) Domin');
  insert into illnesses (name) values ('Bambusa longifolia (Fourn.) McClure');
  insert into illnesses (name) values ('Prunus rivularis Scheele');
  insert into illnesses (name) values ('Thelesperma subnudum A. Gray var. subnudum');
  insert into illnesses (name) values ('Lupinus polycarpus Greene');
  insert into illnesses (name) values ('Adiantum tricholepis Fée');
  insert into illnesses (name) values ('Eupatorium sessilifolium L. var. sessilifolium');
  insert into illnesses (name) values ('Potentilla bimundorum Soják');
  insert into illnesses (name) values ('Agropyron cristatum (L.) Gaertn. ssp. cristatum');
  insert into illnesses (name) values ('Lupinus evermannii Rydb.');
  insert into illnesses (name) values ('Cladonia beaumontii (Tuck.) Vain.');
  insert into illnesses (name) values ('Halenia deflexa (Sm.) Griseb.');
  insert into illnesses (name) values ('Viola palustris L. var. brevipes (M.S. Baker) R.J. Davis');
  insert into illnesses (name) values ('Cocculus carolinus (L.) DC.');
  insert into illnesses (name) values ('Carex cyrtostachya Janeway & Zika');
  insert into illnesses (name) values ('Corylus colurna L.');
  insert into illnesses (name) values ('Allium tolmiei (Hook.) Baker ex S. Watson var. tolmiei');
  insert into illnesses (name) values ('Dioscorea sansibarensis Pax');
  insert into illnesses (name) values ('Castilleja raupii Pennell');
  insert into illnesses (name) values ('Gyalideopsis Vezda');
  insert into illnesses (name) values ('Cladonia atlantica A. Evans');
  insert into illnesses (name) values ('Lupinus diffusus Nutt.');
  insert into illnesses (name) values ('Cladonia didyma (Fée) Vain.');
  insert into illnesses (name) values ('Phaseolus filiformis Benth.');
  insert into illnesses (name) values ('Erysimum pallasii (Pursh) Fernald var. pallasii');
  insert into illnesses (name) values ('Gyalectidium Müll. Arg.');
  insert into illnesses (name) values ('Allium macropetalum Rydb.');
  insert into illnesses (name) values ('Ferocactus eastwoodiae (L.D. Benson) L.D. Benson');
  insert into illnesses (name) values ('Castilleja nervata Eastw.');
  insert into illnesses (name) values ('Caulanthus anceps Payson');
  insert into illnesses (name) values ('Cakile lanceolata (Willd.) O.E. Schulz ssp. lanceolata');
  insert into illnesses (name) values ('Carex praeceptorum Mack.');
  insert into illnesses (name) values ('Balsamorhiza sagittata (Pursh) Nutt.');
  insert into illnesses (name) values ('Heliotropium curassavicum L. var. obovatum DC.');
  insert into illnesses (name) values ('Carex debilis Michx. var. pubera A. Gray');
  insert into illnesses (name) values ('Gymnocarpium jessoense (Koidzumi) Koidzumi ssp. parvulum Sarvela');
  insert into illnesses (name) values ('Hastingsia bracteosa S. Watson var. bracteosa');
  insert into illnesses (name) values ('Bixa orellana L.');
  insert into illnesses (name) values ('Tortella rigens Alb.');
  insert into illnesses (name) values ('Geum ×catlingii J.-P. Bernard & R. Gauthier');
  insert into illnesses (name) values ('Hypoxis juncea Sm.');
  insert into illnesses (name) values ('Fritillaria striata Eastw.');
  insert into illnesses (name) values ('Sphaerophorus globosus (Huds.) Vain. var. gracilis (Müll. Arg.) Zahlbr.');
  insert into illnesses (name) values ('Claytonia sibirica L. var. sibirica');
  insert into illnesses (name) values ('Chaenactis douglasii (Hook.) Hook. & Arn. var. douglasii');
  insert into illnesses (name) values ('Eriogonum palmerianum Reveal');
  insert into illnesses (name) values ('Pleodendron v. Tiegh.');
  insert into illnesses (name) values ('Helianthella castanea Greene');
  insert into illnesses (name) values ('Heuchera merriamii Eastw.');
  insert into illnesses (name) values ('Pedicularis lapponica L.');
  insert into illnesses (name) values ('Holmgrenanthe petrophila (Coville & Morton) Elisens');
  insert into illnesses (name) values ('Lipochaeta remyi A. Gray');
  insert into illnesses (name) values ('Chrysothamnus humilis Greene');
  insert into illnesses (name) values ('Aloe ferox Mill.');
  insert into illnesses (name) values ('Ceratopteris thalictroides (L.) Brongn.');
  insert into illnesses (name) values ('Astragalus mollissimus Torr. var. earlei (Greene ex Rydb.) Tidestr.');
  insert into illnesses (name) values ('Camissonia claviformis (Torr. & Frém.) P.H. Raven ssp. aurantiaca (Munz) P.H. Raven');
  insert into illnesses (name) values ('Streptanthus albidus Greene ssp. peramoenus (Greene) Kruckeb.');
  insert into illnesses (name) values ('Doellingeria umbellata (Mill.) Nees');
  insert into illnesses (name) values ('Graphina acharii (Fée) Müll. Arg.');
  insert into illnesses (name) values ('Cryptantha atwoodii Higgins');
  insert into illnesses (name) values ('Caulanthus cooperi (S. Watson) Payson');
  insert into illnesses (name) values ('Euphrasia L.');
  insert into illnesses (name) values ('Ribes leptanthum A. Gray');
  insert into illnesses (name) values ('Senna durangensis (Rose) Irwin & Barneby var. durangensis');
  insert into illnesses (name) values ('Sageretia thea (Osbeck) M.C. Johnst.');
  insert into illnesses (name) values ('Sagittaria papillosa Buchenau');
  insert into illnesses (name) values ('Lindheimera A. Gray & Engelm.');
  insert into illnesses (name) values ('Thevetia peruviana (Pers.) K. Schum.');
  insert into illnesses (name) values ('Lomatium congdonii J.M. Coult. & Rose');
  insert into illnesses (name) values ('Stylocline psilocarphoides M. Peck');
  insert into illnesses (name) values ('Carex brunnescens (Pers.) Poir. ssp. pacifica Kalela');
  insert into illnesses (name) values ('Pisonia floridana Britton ex Small');
  insert into illnesses (name) values ('Paronychia fastigiata (Raf.) Fernald var. fastigiata');
  insert into illnesses (name) values ('Erigeron gracilis Rydb.');
  insert into illnesses (name) values ('Pterostegia drymarioides Fisch. & C.A. Mey.');
  insert into illnesses (name) values ('Doryopteris pedata (L.) Fée');
  insert into illnesses (name) values ('Ranunculus inamoenus Greene');
  insert into illnesses (name) values ('Ipomoea rupicola House');
  insert into illnesses (name) values ('Torenia asiatica L.');
  insert into illnesses (name) values ('Dendriscocaulon intricatulum (Nyl.) Henssen');
  insert into illnesses (name) values ('Vitex agnus-castus L. var. caerulea Rehder');
  insert into illnesses (name) values ('Stereocaulon Hoffm.');
  insert into illnesses (name) values ('Lecanora canadensis Lynge & H. Magn.');
  insert into illnesses (name) values ('Lupinus croceus Eastw.');
  insert into illnesses (name) values ('Festuca saximontana Rydb.');
  insert into illnesses (name) values ('Verbena bracteata Cav. ex Lag. & Rodr.');
  insert into illnesses (name) values ('Isachne distichophylla Munro ex Hillebr.');
  insert into illnesses (name) values ('Anisacanthus thurberi (Torr.) A. Gray');
  insert into illnesses (name) values ('Cusickiella Rollins');
  insert into illnesses (name) values ('Crataegus castlegarensis J.B. Phipps & R.J.O. Kennon');
  insert into illnesses (name) values ('Muhlenbergia capillaris (Lam.) Trin.');
  insert into illnesses (name) values ('Entada phaseoloides (L.) Merr.');
  insert into illnesses (name) values ('Arenaria fendleri A. Gray var. porteri Rydb.');
  insert into illnesses (name) values ('Symphoricarpos guadalupensis Correll');
  insert into illnesses (name) values ('Physocarpus capitatus (Pursh) Kuntze');
  insert into illnesses (name) values ('Symplocarpus Salisb. ex W.P.C. Barton');
  insert into illnesses (name) values ('Heterotheca oregona (Nutt.) Shinners var. oregona');
  insert into illnesses (name) values ('Piptochaetium avenaceum (L.) Parodi');
  insert into illnesses (name) values ('Diodia teres Walter var. oblongifolia Fernald');
  insert into illnesses (name) values ('Croton californicus Müll. Arg.');
  insert into illnesses (name) values ('Ranunculus sceleratus L. var. sceleratus');
  insert into illnesses (name) values ('Quercus laevis Walter');
  insert into illnesses (name) values ('Solanum lanceifolium Jacq.');
  insert into illnesses (name) values ('Quercus engelmannii Greene');
  insert into illnesses (name) values ('Smelowskia borealis (Greene) Drury & Rollins var. jordalii Drury & Rollins');
  insert into illnesses (name) values ('Carex vestita Willd.');
  insert into illnesses (name) values ('Cladonia acuminata (Ach.) Norrlin');
  insert into illnesses (name) values ('Hirtella triandra Sw.');
  insert into illnesses (name) values ('Polyblastia hyperborea Th. Fr.');
  insert into illnesses (name) values ('Arenaria hookeri Nutt. ssp. desertorum (Maguire) W.A. Weber');
  insert into illnesses (name) values ('Dermatocarpon arnoldianum Degel.');
  insert into illnesses (name) values ('Cosmos Cav.');
  insert into illnesses (name) values ('Plantago princeps Cham. & Schltdl.');
  insert into illnesses (name) values ('Reverchonia A. Gray');
  insert into illnesses (name) values ('Townsendia grandiflora Nutt.');
  insert into illnesses (name) values ('Machaeranthera asteroides (Torr.) Greene var. lagunensis (D.D. Keck) B.L. Turner');
  insert into illnesses (name) values ('Philadelphus pubescens Loisel. var. pubescens');
  insert into illnesses (name) values ('Symphyotrichum yukonense (Cronquist) G.L. Nesom');
  insert into illnesses (name) values ('Pouzolzia Gaudich.');
  insert into illnesses (name) values ('Torilis japonica (Houtt.) DC.');
  insert into illnesses (name) values ('Sphaeralcea bonariensis (Cav.) Griseb.');
  insert into illnesses (name) values ('Gratiola viscidula Pennell');
  insert into illnesses (name) values ('Blepharoneuron Nash');
  insert into illnesses (name) values ('Begonia coccinea Hook.');
  insert into illnesses (name) values ('Clerodendrum glabrum E. Mey.');
  insert into illnesses (name) values ('Caloplaca pollinii (A. Massal.) Jatta');
  insert into illnesses (name) values ('Streptanthus barbiger Greene');
  insert into illnesses (name) values ('Virola Aubl.');
  insert into illnesses (name) values ('Platanthera praeclara Sheviak & Bowles');
  insert into illnesses (name) values ('Carex alma L.H. Bailey');
  insert into illnesses (name) values ('Salix ×princeps-ourayi L. Kelso');
  insert into illnesses (name) values ('Cyclodictyon Mitt.');
  insert into illnesses (name) values ('Sphaeralcea ambigua A. Gray ssp. rosacea (Munz & I.M. Johnst.) Kearney');
  insert into illnesses (name) values ('Leucobryum albidum (Brid. ex P. Beauv.) Lindb.');
  insert into illnesses (name) values ('Trapa natans L.');
  insert into illnesses (name) values ('Lewisia kelloggii K. Brandegee ssp. kelloggii');
  insert into illnesses (name) values ('Eleusine indica (L.) Gaertn.');
  insert into illnesses (name) values ('Phyllanthus L.');
  insert into illnesses (name) values ('Rosa ×odorata (Andrews) Sweet (pro sp.)');
  insert into illnesses (name) values ('Tagetes lemmonii A. Gray');
  insert into illnesses (name) values ('Polyctenium fremontii (S. Watson) Greene');
  insert into illnesses (name) values ('Galeopsis tetrahit L.');
  insert into illnesses (name) values ('Crataegus vailiae Britton');
  insert into illnesses (name) values ('Peperomia pellucida (L.) Kunth');
  insert into illnesses (name) values ('Prunus virginiana L.');
  insert into illnesses (name) values ('Pseudostellaria jamesiana (Torr.) W.A. Weber & R.L. Hartm.');
  insert into illnesses (name) values ('Knautia arvensis (L.) J.M. Coult.');
  insert into illnesses (name) values ('Ficus lyrata Warb.');
  insert into illnesses (name) values ('Carex sprengelii Dewey ex Spreng.');
  insert into illnesses (name) values ('Muhlenbergia emersleyi Vasey');
  insert into illnesses (name) values ('Panicum turgidum Forssk.');
  insert into illnesses (name) values ('Styphnolobium affine (Torr. & A. Gray) Walp.');
  insert into illnesses (name) values ('Atriplex elegans (Moq.) D. Dietr. var. fasciculata (S. Watson) M.E. Jones');
  insert into illnesses (name) values ('Xyris floridana (Kral) E.L. Bridges & Orzell');
  insert into illnesses (name) values ('Carex lupuliformis Sartwell ex Dewey');
  insert into illnesses (name) values ('Alvaradoa Liebm.');
  insert into illnesses (name) values ('Astragalus amblytropis Barneby');
  insert into illnesses (name) values ('Carex ×langeana Fernald (pro sp.)');
  insert into illnesses (name) values ('Ephemerum serratum (Hedw.) Hampe');
  insert into illnesses (name) values ('Aplectrum Torr.');
  insert into illnesses (name) values ('Chlorogalum pomeridianum (DC.) Kunth var. pomeridianum');
  insert into illnesses (name) values ('Horkelia truncata Rydb.');
  insert into illnesses (name) values ('Forsstroemia Lindb.');
  insert into illnesses (name) values ('Holozonia Greene');
  insert into illnesses (name) values ('Potentilla diversifolia Lehm. var. diversifolia');
  insert into illnesses (name) values ('Columnea scandens L. var. tulae (Urb.) Wiehler');
  insert into illnesses (name) values ('Dichondra carolinensis Michx.');
  insert into illnesses (name) values ('Alectoria nigricans (Ach.) Nyl.');
  insert into illnesses (name) values ('Aegilops longissima Schweinf. & Muschl.');
  insert into illnesses (name) values ('Columnea ambigua (Urb.) Morley');
  insert into illnesses (name) values ('Cardamine cordifolia A. Gray var. lyallii (S. Watson) A. Nelson & J.F. Macbr.');
  insert into illnesses (name) values ('Ravenala madagascariensis Sonnerat');
  insert into illnesses (name) values ('Lomariopsis amydrophlebia (Slosson ex Maxon) Holttum');
  insert into illnesses (name) values ('Celtis sinensis Pers.');
  insert into illnesses (name) values ('Eurytaenia Torr. & A. Gray');
  insert into illnesses (name) values ('Firmiana simplex (L.) W. Wight');
  insert into illnesses (name) values ('Bryum algovicum Sendtn. ex Müll. Hal. var. rutheanum (Warnst.) Crundw.');
  insert into illnesses (name) values ('Lupinus excubitus M.E. Jones var. excubitus');
  insert into illnesses (name) values ('Crataegus azarolus L.');
  insert into illnesses (name) values ('Phaeosporobolus usneae D. Hawksw. & Hafellner');
  insert into illnesses (name) values ('Phacelia congdonii Greene');
  insert into illnesses (name) values ('Chimaphila umbellata (L.) W.P.C. Barton ssp. occidentalis (Rydb.) Hultén');
  insert into illnesses (name) values ('Primula cuneifolia Ledeb. ssp. saxifragifolia (Lehm.) W.W. Sm. & G. Forrest');
  insert into illnesses (name) values ('Triteleia Douglas ex Lindl.');
  insert into illnesses (name) values ('Ribes californicum Hook. & Arn.');
  insert into illnesses (name) values ('Viburnum acerifolium L.');
  insert into illnesses (name) values ('Brachyelytrum aristosum (Michx.) Trel.');
  insert into illnesses (name) values ('Lasthenia ferrisiae Ornduff');
  insert into illnesses (name) values ('Drepanocladus aduncus (Hedw.) Warnst. var. polycarpus (Bland. ex Voit) G. Roth');
  insert into illnesses (name) values ('Quercus geminata Small');
  insert into illnesses (name) values ('Flavoparmelia concreta (Stizenb.) ?, ined.?');
  insert into illnesses (name) values ('Dysphania graveolens (Willd.) Mosyakin & Clemants');
  insert into illnesses (name) values ('Brachythecium oedipodium (Mitt.) A. Jaeger');
  insert into illnesses (name) values ('Macroptilium atropurpureum (Moc. & Sessé ex DC.) Urb.');
  insert into illnesses (name) values ('Agathosma Willd.');
  insert into illnesses (name) values ('Allium dichlamydeum Greene');
  insert into illnesses (name) values ('Brothera Müll. Hal.');
  insert into illnesses (name) values ('Datisca glomerata (C. Presl) Baill.');
  insert into illnesses (name) values ('Anemia wrightii Baker');
  insert into illnesses (name) values ('Thelypteris hispidula (Decne.) C.F. Reed var. hispidula');
  insert into illnesses (name) values ('Oxytropis oreophila A. Gray');
  insert into illnesses (name) values ('Luculia Sweet');
  insert into illnesses (name) values ('Dichanthelium acuminatum (Sw.) Gould & C.A. Clark var. fasciculatum (Torr.) Freckmann');
  insert into illnesses (name) values ('Schefflera morototonii (Aubl.) Maguire, Steyerm. & Frodin');
  insert into illnesses (name) values ('Danthonia decumbens (L.) DC.');
  insert into illnesses (name) values ('Roystonea regia (Kunth) O.F. Cook, nom. cons.');
  insert into illnesses (name) values ('Clitoria mariana L.');
  insert into illnesses (name) values ('Iris delavayi Micheli');
  insert into illnesses (name) values ('Ludwigia peploides (Kunth) P.H. Raven ssp. montevidensis (Spreng.) P.H. Raven');
  insert into illnesses (name) values ('Sagraea DC.');
  insert into illnesses (name) values ('Achillea millefolium L. var. californica (Pollard) Jeps.');
  insert into illnesses (name) values ('Pyrrocoma liatriformis Greene');
  insert into illnesses (name) values ('Lonicera albiflora Torr. & A. Gray');
  insert into illnesses (name) values ('Eriophorum callitrix Cham. ex C.A. Mey. var. callitrix');
  insert into illnesses (name) values ('Cylindropuntia ×kelvinensis (V.E. Grant & K.A. Grant) P.V. Heath');
  insert into illnesses (name) values ('Thelotrema subtile Tuck.');
  insert into illnesses (name) values ('Primula borealis Duby');
  insert into illnesses (name) values ('Chenopodium ×variabile Aellen');
  insert into illnesses (name) values ('Lecidea katahdinensis Degel.');
  insert into illnesses (name) values ('Crataegus poliophylla Sarg.');
  insert into illnesses (name) values ('Lecanora caesiorubella Ach. ssp. prolifera (Fink) R.C. Harris');
  insert into illnesses (name) values ('Homaliadelphus Dix. & P. Varde');
  insert into illnesses (name) values ('Acacia chinchillensis Tindale');
  insert into illnesses (name) values ('Hibiscadelphus bombycinus Forbes');
  insert into illnesses (name) values ('Buellia ocellata (Flotow) Körb.');
  insert into illnesses (name) values ('Eurybia wasatchensis (M.E. Jones) G.L. Nesom');
  insert into illnesses (name) values ('Mercurialis L.');
  insert into illnesses (name) values ('Phacelia imbricata Greene');
  insert into illnesses (name) values ('Erucastrum gallicum (Willd.) O.E. Schulz');
  insert into illnesses (name) values ('Cnidoscolus aconitifolius (Mill.) I.M. Johnst.');
  insert into illnesses (name) values ('Actaea pachypoda Elliott');
  insert into illnesses (name) values ('Agrostis elliottiana Schult.');
  insert into illnesses (name) values ('Erigeron strigosus Muhl. ex Willd. var. dolomiticola J. Allison');
  insert into illnesses (name) values ('Bulbostylis vestita (Kunth) C.B. Clarke');
  insert into illnesses (name) values ('Draba stenoloba Ledeb. var. stenoloba');
  insert into illnesses (name) values ('Cheilanthes parryi (D.C. Eaton) Domin');
  insert into illnesses (name) values ('Gyalideopsis athalloides (Nyl.) Vezda');
  insert into illnesses (name) values ('Nolina georgiana Michx.');
  insert into illnesses (name) values ('Thymophylla pentachaeta (DC.) Small');
  insert into illnesses (name) values ('Arctostaphylos manzanita Parry ssp. wieslanderi P.V. Wells');
  insert into illnesses (name) values ('Syrrhopodon texanus Sull.');
  insert into illnesses (name) values ('Labordia pumila (Hillebr.) Skottsb.');
  insert into illnesses (name) values ('Escallonia Mutis ex L. f.');
  insert into illnesses (name) values ('Carex concinnoides Mack.');
  insert into illnesses (name) values ('Eucalyptus ×mortoniana Kinney (pro sp.)');
  insert into illnesses (name) values ('Lactuca sativa L.');
  insert into illnesses (name) values ('Talinum portulacifolium (Forssk.) Asch. ex Schweinf.');
  insert into illnesses (name) values ('Clematis florida Thunb.');
  insert into illnesses (name) values ('Asplenium uniseriale Raddi');
  insert into illnesses (name) values ('Astragalus wetherillii M.E. Jones');
  insert into illnesses (name) values ('Hymenaea L.');
  insert into illnesses (name) values ('Poitea paucifolia (DC.) Lavin');
  insert into illnesses (name) values ('Streptanthus tortuosus Kellogg var. flavescens Jeps.');
  insert into illnesses (name) values ('Arceuthobium littorum Hawksw., Wiens & Nickrent');
  insert into illnesses (name) values ('Mirabilis laevis (Benth.) Curran');
  insert into illnesses (name) values ('Ivesia callida (H.M. Hall) Rydb.');
  insert into illnesses (name) values ('Erigeron piscaticus G.L. Nesom');
  insert into illnesses (name) values ('Cryptantha decipiens (M.E. Jones) A. Heller');
  insert into illnesses (name) values ('Sanicula peckiana J.F. Macbr.');
  insert into illnesses (name) values ('Cyrtandra ×cladantha Skottsb. (pro sp.)');
  insert into illnesses (name) values ('Ornithopus perpusillus L.');
  insert into illnesses (name) values ('Eremalche rotundifolia (A. Gray) Greene');
  insert into illnesses (name) values ('Digitaria patens (Swallen) Henr.');
  insert into illnesses (name) values ('Gloriosa L.');
  insert into illnesses (name) values ('Oxalis drummondii A. Gray');
  insert into illnesses (name) values ('Coreopsis latifolia Michx.');
  insert into illnesses (name) values ('Botrychium mormo W.H. Wagner');
  insert into illnesses (name) values ('Caloplaca castellana (Rasanen) Poelt');
  insert into illnesses (name) values ('Gayophytum diffusum Torr. & A. Gray ssp. diffusum');
  insert into illnesses (name) values ('Eichhornia crassipes (Mart.) Solms');
  insert into illnesses (name) values ('Hieracium praealtum Vill. ex Gochnat var. decipiens W.D.J. Koch');
  insert into illnesses (name) values ('Ionactis Greene');
  insert into illnesses (name) values ('Puccinellia parishii Hitchc.');
  insert into illnesses (name) values ('Vitex trifolia L. var. variegata Moldenke');
  insert into illnesses (name) values ('Lawsonia inermis L.');
  insert into illnesses (name) values ('Phyllanthus caroliniensis Walter');
  insert into illnesses (name) values ('Matelea maritima (Jacq.) Woodson');
  insert into illnesses (name) values ('Packera neomexicana (A. Gray) W.A. Weber & Á. Löve var. metcalfei (Greene) D.K. Trock & T.M. Barkley');
  insert into illnesses (name) values ('Hordeum L.');
  insert into illnesses (name) values ('Boscia senegalensis (Pers.) Lam. ex Poir.');
  insert into illnesses (name) values ('Stellaria graminea L.');
  insert into illnesses (name) values ('Eustoma exaltatum (L.) Salisb. ex G. Don ssp. exaltatum');
  insert into illnesses (name) values ('Rhytidiadelphus squarrosus (Hedw.) Warnst.');
  insert into illnesses (name) values ('Cyperus grayi Torr.');
  insert into illnesses (name) values ('Symphyotrichum hallii (A. Gray) G.L. Nesom');
  insert into illnesses (name) values ('Calystegia subacaulis Hook. & Arn. ssp. subacaulis');
  insert into illnesses (name) values ('Frangula rubra (Greene) V. Grub. ssp. rubra');
  insert into illnesses (name) values ('Rhynchospora latifolia (Baldw. ex Elliott) W.W. Thomas');
  insert into illnesses (name) values ('Hybanthus linearifolius (Vahl) Urb.');
  INSERT INTO illnesses (name) VALUES ('Laryngeal Diphtheria');
  INSERT INTO illnesses (name) VALUES ('Vitiligo');
  INSERT INTO illnesses (name) VALUES ('Pellagra');
  INSERT INTO illnesses (name) VALUES ('Psoriasis');
  INSERT INTO illnesses (name) VALUES ('Stomatitis');
  INSERT INTO illnesses (name) VALUES ('Periapical Abscess');
  INSERT INTO illnesses (name) VALUES ('Infected Socket');
  
