insert into treatments (name) values ('Hemofil M');
insert into treatments (name) values ('Laryng-O-Jet');
insert into treatments (name) values ('CIPROFLOXACIN');
insert into treatments (name) values ('Good Neighbor Pharmacy Pain Relief');
insert into treatments (name) values ('HYDRALAZINE HYDROCHLORIDE');
insert into treatments (name) values ('DOUBLE PERFECTION LUMIERE');
insert into treatments (name) values ('Propranolol Hydrochloride');
insert into treatments (name) values ('ATACAND');
insert into treatments (name) values ('Isradipine');
insert into treatments (name) values ('CELLBOOSTING HOMME WHITENING FLUID');
insert into treatments (name) values ('Pleo Not');
insert into treatments (name) values ('INSOMNIA');
insert into treatments (name) values ('Squash Zucchini');
insert into treatments (name) values ('PRAMIPEXOLE DIHYDROCHLORIDE');
insert into treatments (name) values ('IBANDRONATE SODIUM');
insert into treatments (name) values ('Levothyroxine Sodium');
insert into treatments (name) values ('PredniSONE');
insert into treatments (name) values ('Senna- S');
insert into treatments (name) values ('Sulfasalazine');
insert into treatments (name) values ('Oat Smut');
insert into treatments (name) values ('Omeprazole');
insert into treatments (name) values ('DG Health Ibuprofen');
insert into treatments (name) values ('DulcoGas');
insert into treatments (name) values ('CLARINS BROAD SPECTRUM SPF 50 SUNSCREEN CARE MILK FOR CHILDREN');
insert into treatments (name) values ('Acetaminophen PM');
insert into treatments (name) values ('simvastatin');
insert into treatments (name) values ('Tamiflu');
insert into treatments (name) values ('dg health cold and flu relief');
insert into treatments (name) values ('Levetiracetam');
insert into treatments (name) values ('Norethindrone Acetate');
insert into treatments (name) values ('Lyrica');
insert into treatments (name) values ('Complete Flu Care 4 Kids');
insert into treatments (name) values ('donepezil hydrochloride');
insert into treatments (name) values ('Otis Clapp Ultraprin');
insert into treatments (name) values ('ZOCOR');
insert into treatments (name) values ('EXCHANGE SELECT NICOTINE TRANSDERMAL SYSTEM');
insert into treatments (name) values ('LORTUSS');
insert into treatments (name) values ('DIPYRIDAMOLE');
insert into treatments (name) values ('Pro-Den Rx');
insert into treatments (name) values ('Gildess 1/20');
insert into treatments (name) values ('mally Face Defender Foundation');
insert into treatments (name) values ('Voriconazole');
insert into treatments (name) values ('Dandruff');
insert into treatments (name) values ('Carboplatin');
insert into treatments (name) values ('calcitriol');
insert into treatments (name) values ('Paser');
insert into treatments (name) values ('Hush Anesthetic');
insert into treatments (name) values ('Extra Strength Medicated Body');
insert into treatments (name) values ('Ceftriaxone Sodium');
insert into treatments (name) values ('KETOCONAZOLE');
insert into treatments (name) values ('Antiseptic');
insert into treatments (name) values ('Bacitracin');
insert into treatments (name) values ('Sesame Seed');
insert into treatments (name) values ('INSTA-CHAR AQUEOUS CHERRY');
insert into treatments (name) values ('AHC Collagen Serum');
insert into treatments (name) values ('RHEUMATISM');
insert into treatments (name) values ('Topical 60 Sec Sodium Fluoride');
insert into treatments (name) values ('dayhist allergy');
insert into treatments (name) values ('Hang Over RELIEF');
insert into treatments (name) values ('Homeopathic Hangover Formula');
insert into treatments (name) values ('Garnier Fructis Antidandruff');
insert into treatments (name) values ('Wheat Smut');
insert into treatments (name) values ('CLARINS Broad Spectrum SPF 15 Sunscreen Extra-Firming Foundation Tint 110');
insert into treatments (name) values ('Pollens - Trees, Maple, Hard Acer saccharum');
insert into treatments (name) values ('FORTAMET');
insert into treatments (name) values ('ECZEMA AND PSORIASIS FREE');
insert into treatments (name) values ('Alka-Seltzer XTRA STRENGTH');
insert into treatments (name) values ('Leader Sore throat');
insert into treatments (name) values ('Acetaminophen');
insert into treatments (name) values ('Nitrofurantoin Macrocrystals');
insert into treatments (name) values ('Ondansetron Hydrochloride');
insert into treatments (name) values ('Atorvastatin Calcium');
insert into treatments (name) values ('Glynase');
insert into treatments (name) values ('Tramadol Hydrochloride');
insert into treatments (name) values ('Clear-Tone Antibacterial Hand');
insert into treatments (name) values ('Good Sense Night Time');
insert into treatments (name) values ('Chestnut');
insert into treatments (name) values ('GERI-LANTA SUPREME CHERRY');
insert into treatments (name) values ('Finasteride');
insert into treatments (name) values ('SULFASALAZINE');
insert into treatments (name) values ('Thyro Tonic');
insert into treatments (name) values ('Benztropine Mesylate');
insert into treatments (name) values ('Natures Gate');
insert into treatments (name) values ('SUCRALFATE');
insert into treatments (name) values ('Ibuprofen');
insert into treatments (name) values ('White Pepper');
insert into treatments (name) values ('Standardized Mite D. pteronyssinus');
insert into treatments (name) values ('FLONASE');
insert into treatments (name) values ('Diabenex');
insert into treatments (name) values ('Meclizine Hydrochloride');
insert into treatments (name) values ('Pollens - Trees, Bottlebrush, Callistemon spp.');
insert into treatments (name) values ('Flu Relief Therapy Night Time');
insert into treatments (name) values ('NataChew');
insert into treatments (name) values ('Pollens - Weeds and Garden Plants, Lambs Quarters Chenopodium album');
insert into treatments (name) values ('Daytime Cold and Flu Relief');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('Doxycycline Hyclate');
insert into treatments (name) values ('FRAICHEUR VERVEINE ANTIPERSPIRANT AND DEODORANT ROLL-ON');
insert into treatments (name) values ('NU-DERM Tolereen');
insert into treatments (name) values ('Meloxicam');
insert into treatments (name) values ('Metformin Hydrochloride');
insert into treatments (name) values ('Theophylline');
insert into treatments (name) values ('Fluconazole');
insert into treatments (name) values ('Hand Sanitizer');
insert into treatments (name) values ('HGH Complex');
insert into treatments (name) values ('Doxycycline Hyclate');
insert into treatments (name) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into treatments (name) values ('Hog Epithelium');
insert into treatments (name) values ('Olay Total Effects Blemish Control');
insert into treatments (name) values ('CETAFEN EXTRA');
insert into treatments (name) values ('CIPROFLOXACIN');
insert into treatments (name) values ('Sodium Sulfacetamide');
insert into treatments (name) values ('VITALUMIERE AQUA');
insert into treatments (name) values ('Pollens - Trees, Palo Verde Cercidium floridum');
insert into treatments (name) values ('Sumatriptan Succinate');
insert into treatments (name) values ('Albuterol Sulfate');
insert into treatments (name) values ('Zicam');
insert into treatments (name) values ('CETIRIZINE HYDROCHLORIDE');
insert into treatments (name) values ('McKesson Unna Boot with Calamine 4');
insert into treatments (name) values ('Diclofenac Sodium');
insert into treatments (name) values ('HUNGARIAN SMOOTH BROME POLLEN');
insert into treatments (name) values ('nystatin');
insert into treatments (name) values ('Cimetidine');
insert into treatments (name) values ('Anti-Aging Vitamin Complex 7-in-1 Broad Spectrum SPF15 Sunscreen');
insert into treatments (name) values ('RELNATE DHA');
insert into treatments (name) values ('hydroxyzine pamoate');
insert into treatments (name) values ('Gehwol Foot and Shoe Deodorant');
insert into treatments (name) values ('Western Ragweed');
insert into treatments (name) values ('Extra Strength Pain Reliever');
insert into treatments (name) values ('Principal Secret');
insert into treatments (name) values ('Carisoprodol');
insert into treatments (name) values ('pain relief pm');
insert into treatments (name) values ('RHODOTORULA RUBRA');
insert into treatments (name) values ('Birch');
insert into treatments (name) values ('Glytone Clarifying');
insert into treatments (name) values ('Bravelle');
insert into treatments (name) values ('Theraflu');
insert into treatments (name) values ('bacitracin zinc, neomycin sulfate and polymyxin b sulfate');
insert into treatments (name) values ('LIFT LUMIERE');
insert into treatments (name) values ('Erythromycin');
insert into treatments (name) values ('Fleet');
insert into treatments (name) values ('Ferrum sidereum Pancreas 10/4 Special Order');
insert into treatments (name) values ('COLAZAL');
insert into treatments (name) values ('Chagrined');
insert into treatments (name) values ('Moisture Therapy');
insert into treatments (name) values ('Glimepiride');
insert into treatments (name) values ('Skelaxin');
insert into treatments (name) values ('Desoximetasone');
insert into treatments (name) values ('Naproxen');
insert into treatments (name) values ('Hormodendrum');
insert into treatments (name) values ('Sleep Aid');
insert into treatments (name) values ('La mer Hand Sanitizer');
insert into treatments (name) values ('Propranolol Hydrochloride');
insert into treatments (name) values ('Acetaminophen');
insert into treatments (name) values ('Ranitidine');
insert into treatments (name) values ('Leader Acid Control');
insert into treatments (name) values ('Amoxicillin');
insert into treatments (name) values ('HEMORRHOIDS PROCTALGIA');
insert into treatments (name) values ('antacid');
insert into treatments (name) values ('Felodipine');
insert into treatments (name) values ('Amantadine Hydrochloride');
insert into treatments (name) values ('ACETAMINOPHEN');
insert into treatments (name) values ('Nervousness - Anxiety');
insert into treatments (name) values ('rea lo 40');
insert into treatments (name) values ('Ceramide Lift and Firm Makeup Broad Spectrum Sunscreen SPF 15 Vanilla Shell');
insert into treatments (name) values ('Tilia Fe');
insert into treatments (name) values ('Hydroxyzine Hydrochloride');
insert into treatments (name) values ('Fungi Nail Toe and Foot Pen');
insert into treatments (name) values ('CENTER-AL - JUGLANS CALIFORNICA POLLEN');
insert into treatments (name) values ('DRISDOL');
insert into treatments (name) values ('JUBLIA');
insert into treatments (name) values ('Carbamazepine');
insert into treatments (name) values ('BENZTROPINE MESYLATE');
insert into treatments (name) values ('ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into treatments (name) values ('Headache Soothe');
insert into treatments (name) values ('XIFAXAN');
insert into treatments (name) values ('Levetiracetam');
insert into treatments (name) values ('ThyroShield');
insert into treatments (name) values ('Pleo Mucedo');
insert into treatments (name) values ('Ultimate Rescue');
insert into treatments (name) values ('Alka-Seltzer Plus Night Severe Cold, Cough And Flu');
insert into treatments (name) values ('Ranitidine');
insert into treatments (name) values ('FLONASE');
insert into treatments (name) values ('Childrens Cold and Cough');
insert into treatments (name) values ('Triple Antibiotic');
insert into treatments (name) values ('Azithromycin');
insert into treatments (name) values ('hydrocodone bitartrate and acetaminophen');
insert into treatments (name) values ('smart sense ibuprofen pm');
insert into treatments (name) values ('Sumatriptan Succinate');
insert into treatments (name) values ('Luminous Bright Aura CC');
insert into treatments (name) values ('Anti-Bacterial Hand');
insert into treatments (name) values ('Dopamine');
insert into treatments (name) values ('Koate');
insert into treatments (name) values ('Clarithromycin');
insert into treatments (name) values ('Allerpoll');
insert into treatments (name) values ('Headache');
insert into treatments (name) values ('JUVISYNC');
insert into treatments (name) values ('Auro Earache Relief');
insert into treatments (name) values ('Prazosin Hydrochloride');
insert into treatments (name) values ('Marsh Elder Mixture');
insert into treatments (name) values ('CPDA-1');
insert into treatments (name) values ('pravastatin sodium');
insert into treatments (name) values ('Arm and Hammer Baking Soda');
insert into treatments (name) values ('Promescent');
insert into treatments (name) values ('Oxygen-Helium Mixture');
insert into treatments (name) values ('Olanzapine');
insert into treatments (name) values ('Candesartan Cilexetil-Hydrochlorothiazide');
insert into treatments (name) values ('Germ Bullet');
insert into treatments (name) values ('EQUUS CABALLUS SKIN');
insert into treatments (name) values ('Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate and Amphetamine Sulfate');
insert into treatments (name) values ('Levetiracetam');
insert into treatments (name) values ('ManzanillaSophia');
insert into treatments (name) values ('Hydrochlorothiazide');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('Lipiodol Ultra-Fluide');
insert into treatments (name) values ('Levothyroxine Sodium');
insert into treatments (name) values ('DoctorRelief');
insert into treatments (name) values ('Lyrica');
insert into treatments (name) values ('Amlodipine Besylate');
insert into treatments (name) values ('Atenolol');
insert into treatments (name) values ('RHEUMATISM, NAUSEA');
insert into treatments (name) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into treatments (name) values ('SMART SENSE');
insert into treatments (name) values ('Allopurinol');
insert into treatments (name) values ('VioNexus');
insert into treatments (name) values ('SUPREP Bowel Prep');
insert into treatments (name) values ('SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)');
insert into treatments (name) values ('Dove Ultimate Go Fresh');
insert into treatments (name) values ('CORTEF');
insert into treatments (name) values ('Walgreens Oil-Free Acne Wash');
insert into treatments (name) values ('EPICOCCUM NIGRUM');
insert into treatments (name) values ('Personal Care Petroleum Jelly Skin Protectant');
insert into treatments (name) values ('Buspirone Hydrochloride');
insert into treatments (name) values ('Citalopram');
insert into treatments (name) values ('Prednisone');
insert into treatments (name) values ('good neighbor pharmacy sinus');
insert into treatments (name) values ('Sevoflurane');
insert into treatments (name) values ('Fosinopril sodium');
insert into treatments (name) values ('Carvedilol');
insert into treatments (name) values ('METHIMAZOLE');
insert into treatments (name) values ('On Duty 24 Hours Clear Protection');
insert into treatments (name) values ('Doxorubicin Hydrochloride');
insert into treatments (name) values ('SHISEIDO SUNCARE ULTIMATE');
insert into treatments (name) values ('Thursday Plantation');
insert into treatments (name) values ('Hydrogen Peroxide');
insert into treatments (name) values ('Gluten Sensitivity Formula');
insert into treatments (name) values ('gentle lax');
insert into treatments (name) values ('Antispetic');
insert into treatments (name) values ('INDOMETHACIN ER');
insert into treatments (name) values ('The Prestige BB SPF25 PA 2Plus');
insert into treatments (name) values ('Acetaminophen');
insert into treatments (name) values ('CINA');
insert into treatments (name) values ('Chicken Meat');
insert into treatments (name) values ('Piroxicam');
insert into treatments (name) values ('Male Stimulant');
insert into treatments (name) values ('Risperidone');
insert into treatments (name) values ('Citrus Breeze Antibacterial Foaming Hand Wash');
insert into treatments (name) values ('Acne Rescue');
insert into treatments (name) values ('TYLENOL with Codeine');
insert into treatments (name) values ('Safeway');
insert into treatments (name) values ('Dicyclomine Hydrochloride');
insert into treatments (name) values ('Anusol HC');
insert into treatments (name) values ('Yves Saint Laurent');
insert into treatments (name) values ('good neighbor pharmacy ibuprofen pm');
insert into treatments (name) values ('AV3712501 Mineral Sunscreen SPF 18');
insert into treatments (name) values ('Iodine Plus Capsule');
insert into treatments (name) values ('Nadolol');
insert into treatments (name) values ('Vancomycin Hydrochloride');
insert into treatments (name) values ('Aire-Master');
insert into treatments (name) values ('equate daytime');
insert into treatments (name) values ('care one anti diarrheal');
insert into treatments (name) values ('Doxycycline Hyclate');
insert into treatments (name) values ('lansoprazole');
insert into treatments (name) values ('Sore Throat');
insert into treatments (name) values ('dantrolene sodium');
insert into treatments (name) values ('Almond Antibacterial Hand Sanitizer');
insert into treatments (name) values ('Amiodarone Hydrochloride');
insert into treatments (name) values ('Idarubicin Hydrochloride');
insert into treatments (name) values ('Sulfamethoxazole and Trimethoprim');
insert into treatments (name) values ('Sunmark Acid Reducer');
insert into treatments (name) values ('Sunbrellas Mineral Sunblock SPF 30');
insert into treatments (name) values ('Quinine Sulfate');
insert into treatments (name) values ('GRANIX');
insert into treatments (name) values ('RosaRex');
insert into treatments (name) values ('Benicar Hct');
insert into treatments (name) values ('Epicoccum nigrum');
insert into treatments (name) values ('Neutrogena Rapid Clear Stubborn Acne Spot');
insert into treatments (name) values ('Banana Boat Ultra Defense Sheer Protect FPS 50 LATAM');
insert into treatments (name) values ('Childrens Ibuprofen');
insert into treatments (name) values ('ABILIFY');
insert into treatments (name) values ('Cefadroxil');
insert into treatments (name) values ('Flawless Finish Dual Perfection Makeup SPF 8 Sunbeige');
insert into treatments (name) values ('Amiloride Hydrochloride');
insert into treatments (name) values ('Dust Mix Antigens');
insert into treatments (name) values ('Lisinopril 2.5mg');
insert into treatments (name) values ('Sufentanil Citrate');
insert into treatments (name) values ('Forest Sap Patch');
insert into treatments (name) values ('Hydrocortisone');
insert into treatments (name) values ('Passion Flower Antibacterial Foaming Hand Wash');
insert into treatments (name) values ('POTASSIUM CHLORIDE');
insert into treatments (name) values ('Trileptal');
insert into treatments (name) values ('Chlorpromazine Hydrochloride');
insert into treatments (name) values ('Hydrocodone Bitartrate And Acetaminophen');
insert into treatments (name) values ('Red Kidney Beans');
insert into treatments (name) values ('Neut');
insert into treatments (name) values ('AllerguEase Food and Chemical');
insert into treatments (name) values ('Erythromycin');
insert into treatments (name) values ('C-Nate DHA');
insert into treatments (name) values ('Triamcinolone Acetonide');
insert into treatments (name) values ('Pacifica CC broad spectrum SPF 17 LIGHT');
insert into treatments (name) values ('Terrasil Itch, Rash and Pain Relief');
insert into treatments (name) values ('Natrum Phos Kit Refill');
insert into treatments (name) values ('Motion Sickness Relief');
insert into treatments (name) values ('Maalox');
insert into treatments (name) values ('DEMEROL');
insert into treatments (name) values ('IVA ANNUA VAR ANNUA POLLEN');
insert into treatments (name) values ('Allegheny Antibac');
insert into treatments (name) values ('Clindamycin Hydrochloride');
insert into treatments (name) values ('Glimepiride');
insert into treatments (name) values ('Tanzeum');
insert into treatments (name) values ('Sodium Chloride');
insert into treatments (name) values ('LBel');
insert into treatments (name) values ('TENIVAC');
insert into treatments (name) values ('Ropinirole');
insert into treatments (name) values ('ESIKA');
insert into treatments (name) values ('Mucus-Clear');
insert into treatments (name) values ('Sterile Water');
insert into treatments (name) values ('CAREALL Vitamin A and D');
insert into treatments (name) values ('Famotidine');
insert into treatments (name) values ('equaline stomach relief');
insert into treatments (name) values ('Shortleaf Pine');
insert into treatments (name) values ('Salicylic Acid');
insert into treatments (name) values ('BioTPres');
insert into treatments (name) values ('Rite Aid Original Strength Vagicaine');
insert into treatments (name) values ('Calcium Carbonate');
insert into treatments (name) values ('Intensive Scal Care Shampoo');
insert into treatments (name) values ('MOZI-Q');
insert into treatments (name) values ('Nitrous Oxide');
insert into treatments (name) values ('Lyrica');
insert into treatments (name) values ('SUPRAX');
insert into treatments (name) values ('ATORVASTATIN CALCIUM');
insert into treatments (name) values ('Good Sense Complete Lice Treatment');
insert into treatments (name) values ('Meclizine Hydrochloride');
insert into treatments (name) values ('Icy Hot Arthritis');
insert into treatments (name) values ('Rimmel London');
insert into treatments (name) values ('Zosyn');
insert into treatments (name) values ('Eight Hour Cream Lip Protectant SPF 15');
insert into treatments (name) values ('Ketorolac Tromethamine');
insert into treatments (name) values ('CLEAR CELL Medicated Acne Scrub');
insert into treatments (name) values ('Silafed');
insert into treatments (name) values ('Burweed Marsh Elder');
insert into treatments (name) values ('Burkhart');
insert into treatments (name) values ('Bacitracin Zinc');
insert into treatments (name) values ('ampicillin');
insert into treatments (name) values ('The Natural Dentist');
insert into treatments (name) values ('Pain Relief');
insert into treatments (name) values ('Cold Spot');
insert into treatments (name) values ('Ativan');
insert into treatments (name) values ('MINIPRIN');
insert into treatments (name) values ('Wingscale');
insert into treatments (name) values ('Ropinirole Hydrochloride');
insert into treatments (name) values ('Preferred Plus Hemorrhoid');
insert into treatments (name) values ('Mulberry');
insert into treatments (name) values ('ZINACEF');
insert into treatments (name) values ('Propranolol Hydrochloride');
insert into treatments (name) values ('Terazosin');
insert into treatments (name) values ('Namenda');
insert into treatments (name) values ('ACETALDEHYDE');
insert into treatments (name) values ('Bio-Scriptives Lidum Hemorroidal (Anorectal)');
insert into treatments (name) values ('CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 108');
insert into treatments (name) values ('CORYLUS AMERICANA POLLEN');
insert into treatments (name) values ('Zolpidem Tartrate');
insert into treatments (name) values ('Badger SPF 35 Kids All Season');
insert into treatments (name) values ('Total Antimony');
insert into treatments (name) values ('Amiodarone hydrochloride');
insert into treatments (name) values ('Gelato Topical Anesthetic');
insert into treatments (name) values ('SORGHUM HALEPENSE POLLEN');
insert into treatments (name) values ('Calcitriol');
insert into treatments (name) values ('Carvedilol');
insert into treatments (name) values ('GIVEN BY NATURE BAMBOO MASK SHEET');
insert into treatments (name) values ('PERFECTION LUMIERE');
insert into treatments (name) values ('Moisture Renew');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('Atenolol');
insert into treatments (name) values ('Venlafaxine Hydrochloride');
insert into treatments (name) values ('Toppik Mens Hair Regrowth Treatment');
insert into treatments (name) values ('Benazepril Hydrochloride');
insert into treatments (name) values ('Groundsel');
insert into treatments (name) values ('FLOVENT');
insert into treatments (name) values ('Sterile Water');
insert into treatments (name) values ('Enteric Coated Low Dose Aspirin');
insert into treatments (name) values ('Furosemide');
insert into treatments (name) values ('aspirin');
insert into treatments (name) values ('Furosemide');
insert into treatments (name) values ('Breo Ellipta');
insert into treatments (name) values ('Magnesium Hydroxide');
insert into treatments (name) values ('Leader Lubricating plus');
insert into treatments (name) values ('cephalexin');
insert into treatments (name) values ('CVS');
insert into treatments (name) values ('Fanapt');
insert into treatments (name) values ('In Control Nicotine');
insert into treatments (name) values ('dg health all day pain relief');
insert into treatments (name) values ('PAIN RELIEF THERAPY PATCH');
insert into treatments (name) values ('Odyssey');
insert into treatments (name) values ('Pain Relief');
insert into treatments (name) values ('DG Health Mucus Relief');
insert into treatments (name) values ('REFRESH PLUS');
insert into treatments (name) values ('acetaminophen pm');
insert into treatments (name) values ('equaline childrens pain and fever');
insert into treatments (name) values ('KROGER');
insert into treatments (name) values ('Anti-Bacterial Hand');
insert into treatments (name) values ('Blackberry');
insert into treatments (name) values ('ACETAMINOPHEN AND CODEINE PHOSPHATE');
insert into treatments (name) values ('Lorazepam');
insert into treatments (name) values ('Zyclara');
insert into treatments (name) values ('Antibacterial Hand');
insert into treatments (name) values ('QUERCUS AGRIFOLIA POLLEN');
insert into treatments (name) values ('Xpect Buffered Eyewash Sterile Isotonic');
insert into treatments (name) values ('Advanced Whitening Anticavity Fluoride');
insert into treatments (name) values ('Baby Diaper Rash');
insert into treatments (name) values ('Namenda');
insert into treatments (name) values ('Pollens - Trees, Cedar, Red Juniperus virginiana');
insert into treatments (name) values ('Glumetza');
insert into treatments (name) values ('Super Restorative Tinted SPF 20 Tint 1');
insert into treatments (name) values ('Aspirin');
insert into treatments (name) values ('AGE DEFYING HYDRATING SUNSCREEN');
insert into treatments (name) values ('VITAL');
insert into treatments (name) values ('Chip Cravings');
insert into treatments (name) values ('SENSI CARE CLEAR ZINC');
insert into treatments (name) values ('DILTIAZEM HYDROCHLORIDE');
insert into treatments (name) values ('Bio-S-Pres');
insert into treatments (name) values ('CRIXIVAN');
insert into treatments (name) values ('Brazil Nut');
insert into treatments (name) values ('Sodium Polystyrene Sulfonate');
insert into treatments (name) values ('Losartan potassium and Hydrochlorothiazide');
insert into treatments (name) values ('Levofloxacin');
insert into treatments (name) values ('Misoprostol');
insert into treatments (name) values ('Benazepril hydrochloride');
insert into treatments (name) values ('Codeine Sulfate');
insert into treatments (name) values ('LABETALOL HYDROCHLORIDE');
insert into treatments (name) values ('Menopause');
insert into treatments (name) values ('Suboxone');
insert into treatments (name) values ('quetiapine fumarate');
insert into treatments (name) values ('PhysiciansCare Cold and Cough');
insert into treatments (name) values ('HYDROXYUREA');
insert into treatments (name) values ('Health Mart Sinus and Cold D');
insert into treatments (name) values ('Tolterodine Tartrate');
insert into treatments (name) values ('PERFECTION LUMIERE');
insert into treatments (name) values ('Risperidone');
insert into treatments (name) values ('Goose Feathers');
insert into treatments (name) values ('Skintegrity Foaming Hand Sanitizer');
insert into treatments (name) values ('Metoprolol Tartrate');
insert into treatments (name) values ('Home 360 Ultra Dish Detergent Green Apple Scent');
insert into treatments (name) values ('Family Wellness Antifungal');
insert into treatments (name) values ('ALL YOU NEED');
insert into treatments (name) values ('LIGHT THE WAY');
insert into treatments (name) values ('Hydrogen Peroxide');
insert into treatments (name) values ('oxycodone hydrochloride');
insert into treatments (name) values ('Moisturizing Lip BalmSPF30');
insert into treatments (name) values ('CENTER-AL - ULMUS PUMILA POLLEN');
insert into treatments (name) values ('Depo-Medrol');
insert into treatments (name) values ('Cymbalta');
insert into treatments (name) values ('Lupron Depot-PED');
insert into treatments (name) values ('Methscopolamine Bromide');
insert into treatments (name) values ('Oxytocin');
insert into treatments (name) values ('Clarithromycin');
insert into treatments (name) values ('leader acid reducer complete');
insert into treatments (name) values ('RISPERIDONE');
insert into treatments (name) values ('Acyclovir');
insert into treatments (name) values ('Lyrica');
insert into treatments (name) values ('Esika Men Dandruff');
insert into treatments (name) values ('Silky Finish');
insert into treatments (name) values ('Doxepin Hydrochloride');
insert into treatments (name) values ('Antibacterial Hand');
insert into treatments (name) values ('Hand Sanitizer');
insert into treatments (name) values ('GUNA-IL 5');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('Rugby');
insert into treatments (name) values ('Arnica Aurum 20/30');
insert into treatments (name) values ('Metoclopramide');
insert into treatments (name) values ('LEVETIRACETAM');
insert into treatments (name) values ('XtraCare Foam Antibacterial Hand Wash');
insert into treatments (name) values ('Ramipril');
insert into treatments (name) values ('Pumpkin Seeds Antibacterial Foaming Hand Wash');
insert into treatments (name) values ('Sei Bella Skin Refining Tinted Moisturizer');
insert into treatments (name) values ('Blackberry');
insert into treatments (name) values ('Abstral');
insert into treatments (name) values ('Perindopril Erbumine');
insert into treatments (name) values ('Premarin');
insert into treatments (name) values ('Herring');
insert into treatments (name) values ('Extra Strength Pain Reliever');
insert into treatments (name) values ('ARNICA MONTANA (Whole Plant)');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('Gablofen');
insert into treatments (name) values ('Humco Castor Oil');
insert into treatments (name) values ('Mirtazapine');
insert into treatments (name) values ('equate Nicotine');
insert into treatments (name) values ('WHITE CAVIAR ILLUMINATING HAND SUNSCREEN BROAD SPECTRUM SPF 15');
insert into treatments (name) values ('Megestrol Acetate');
insert into treatments (name) values ('Topex');
insert into treatments (name) values ('Chlordiazepoxide Hydrochloride');
insert into treatments (name) values ('Phenobarbital');
insert into treatments (name) values ('Candesartan Cilexetil and Hydrochlorothiazide');
insert into treatments (name) values ('Adult Tussin DM Max');
insert into treatments (name) values ('Ziprasidone Hydrochloride');
insert into treatments (name) values ('Clarithromycin');
insert into treatments (name) values ('Jock Itch');
insert into treatments (name) values ('Antiseptic Hand Gel');
insert into treatments (name) values ('Garlic');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('allergy relief');
insert into treatments (name) values ('ciclopirox olamine');
insert into treatments (name) values ('Cephalexin');
insert into treatments (name) values ('GABAPENTIN');
insert into treatments (name) values ('Sweet Vernal Grass, Standardized');
insert into treatments (name) values ('BUFFERIN');
insert into treatments (name) values ('The New Parent First Aid');
insert into treatments (name) values ('FLAWLESS FINISH PERFECTLY NUDE MAKEUP BROAD SPECTRUM SUNSCREEN SPF 15 SHADE WARM MAHOGANY');
insert into treatments (name) values ('Se-Tan PLUS');
insert into treatments (name) values ('Doxazosin');
insert into treatments (name) values ('Loratadine and Pseudoephedrine');
insert into treatments (name) values ('Epicoccum nigrum');
insert into treatments (name) values ('Femara');
insert into treatments (name) values ('FRESH DECOR');
insert into treatments (name) values ('Good Neighbor Pharmacy Sinus and Allergy PE');
insert into treatments (name) values ('Escitalopram');
insert into treatments (name) values ('Acetaminophen');
insert into treatments (name) values ('Blistex');
insert into treatments (name) values ('Torsemide');
insert into treatments (name) values ('Gabapentin');
insert into treatments (name) values ('OPANA');
insert into treatments (name) values ('Handy Solutions Antiseptic Towelette');
insert into treatments (name) values ('Treatment Set TS335061');
insert into treatments (name) values ('METHYLPREDNISOLONE');
insert into treatments (name) values ('Fentanyl');
insert into treatments (name) values ('VECURONIUM BROMIDE');
insert into treatments (name) values ('English Walnut');
insert into treatments (name) values ('ULTRAM');
insert into treatments (name) values ('Lisinopril');
insert into treatments (name) values ('Spotless Cleanser');
insert into treatments (name) values ('SODIUM HYDROXIDE');
insert into treatments (name) values ('Amlodipine Besylate');
insert into treatments (name) values ('good neighbor pharmacy childrens mucus relief');
insert into treatments (name) values ('PRADAXA');
insert into treatments (name) values ('Smooth (Tag) Alder');
insert into treatments (name) values ('RENOKIN HAIR REVITALIZING');
insert into treatments (name) values ('Metoprolol Succinate');
insert into treatments (name) values ('Ceramide Lift And Firm Makeup Broad Spectrum Sunscreen SPF 15 Buff');
insert into treatments (name) values ('meijer');
insert into treatments (name) values ('Glipizide');
insert into treatments (name) values ('Simvastatin');
insert into treatments (name) values ('Prevail');
insert into treatments (name) values ('Diphenhist');
insert into treatments (name) values ('Lovenox');
insert into treatments (name) values ('PYRETHRUM CINERARIIFOLIUM');
insert into treatments (name) values ('donepezil hydrochloride');
insert into treatments (name) values ('Haloperidol');
insert into treatments (name) values ('healthy accents ibuprofen');
insert into treatments (name) values ('Fluconazole');
insert into treatments (name) values ('Neutrogena Ultra Sheer Body Mist');
insert into treatments (name) values ('Neutrogena Mineral Sheers');
insert into treatments (name) values ('Olanzapine');
insert into treatments (name) values ('Epstein Barr Virus Remedy');
insert into treatments (name) values ('BETHANECHOL CHLORIDE');
insert into treatments (name) values ('Phentermine Hydrochloride');
insert into treatments (name) values ('GRANISETRON HYDROCHLORIDE');
insert into treatments (name) values ('Triple Antibiotic');
insert into treatments (name) values ('No7 Stay Perfect Foundation Sunscreen SPF 15 New Ivory');
insert into treatments (name) values ('Treatment Set TS334128');
insert into treatments (name) values ('Cleocin Hydrochloride');
insert into treatments (name) values ('Plasbumin');
insert into treatments (name) values ('Diazepam');
insert into treatments (name) values ('Pollens - Trees, Boxelder/Maple Mix');
insert into treatments (name) values ('ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25');
insert into treatments (name) values ('CY BETTER LIPS BALM Humectante para Labios con color FPS 18');
insert into treatments (name) values ('NITROGEN');
insert into treatments (name) values ('UTA');
insert into treatments (name) values ('Ultra Seal Bacitracin');
insert into treatments (name) values ('Cold - Sinus');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('Hyoscyamine Sulfate');
insert into treatments (name) values ('Fresh Umbrian Clay Freshface Foundation SPF 20 Sun Empress');
insert into treatments (name) values ('Rodan and Fields');
insert into treatments (name) values ('Quetiapine fumarate');
insert into treatments (name) values ('mally Poreless Perfection Glowing Foundation Medium');
insert into treatments (name) values ('Rite Aid Anti-Cavity, Anti-Gingivitis');
insert into treatments (name) values ('Cefprozil');
insert into treatments (name) values ('Mandragora Rheum');
insert into treatments (name) values ('Softlips');
insert into treatments (name) values ('Candida - Yeast');
insert into treatments (name) values ('Esoterica');
insert into treatments (name) values ('simvastatin');
insert into treatments (name) values ('Ice Elements');
insert into treatments (name) values ('CLADOSPORIUM CLADOSPORIOIDES');
insert into treatments (name) values ('ShopRite Acid Reducer');
insert into treatments (name) values ('imiquimod');
insert into treatments (name) values ('Nigrospora');
insert into treatments (name) values ('Salt Grass');
insert into treatments (name) values ('ESIKA');
insert into treatments (name) values ('Asepxia');
insert into treatments (name) values ('bupropion');
insert into treatments (name) values ('Scar Remover');
insert into treatments (name) values ('Diltiazem Hydrochloride');
insert into treatments (name) values ('DEXTROMETHORPHAN HYDROBROMIDE');
insert into treatments (name) values ('Escitalopram Oxalate');
insert into treatments (name) values ('Mesalamine');
insert into treatments (name) values ('ropinirole hydrochloride');
insert into treatments (name) values ('Sertraline Hydrochloride');
insert into treatments (name) values ('Scott Triclosan Free Antibacterial Skin Cleanser');
insert into treatments (name) values ('pravastatin sodium');
insert into treatments (name) values ('Jute');
insert into treatments (name) values ('Tussnex FM Cold and Sinus');
insert into treatments (name) values ('Tamoxifen Citrate');
insert into treatments (name) values ('Hand Sanitizer');
insert into treatments (name) values ('Salicylic acid');
insert into treatments (name) values ('Inon Ace');
insert into treatments (name) values ('Dial Tropical Escape Antibacterial Body Wash');
insert into treatments (name) values ('Edometriosis');
insert into treatments (name) values ('Baclofen');
insert into treatments (name) values ('Zolpidem Tartrate');
insert into treatments (name) values ('Ecoderm');
insert into treatments (name) values ('Furosemide');
insert into treatments (name) values ('ACETAMINOPHEN AND CODEINE PHOSPHATE');
insert into treatments (name) values ('Detox and Drainage, Blood and Kidney');
insert into treatments (name) values ('Belucie Luxury Timeless Golden Age Eye');
insert into treatments (name) values ('Preferred Plus Severe Nite Time');
insert into treatments (name) values ('Verticillium');
insert into treatments (name) values ('EARTHS CARE ANTI-ITCH');
insert into treatments (name) values ('Treatment Set TS351030');
insert into treatments (name) values ('Captopril');
insert into treatments (name) values ('CENTER-AL - FAGUS GRANDIFOLIA POLLEN');
insert into treatments (name) values ('Dr.Jart CC Essence Balm 01 Light - Medium');
insert into treatments (name) values ('Fragmin');
insert into treatments (name) values ('ETOPOPHOS');
insert into treatments (name) values ('SENEXON-S');
insert into treatments (name) values ('Neova DNA Damage Control - Active');
insert into treatments (name) values ('Aveeno Active Naturals Positively Ageless Correcting Tinted Moisturizer');
insert into treatments (name) values ('Codeine sulfate');
insert into treatments (name) values ('Red Mulberry');
insert into treatments (name) values ('Abstral');
insert into treatments (name) values ('Fioricet with Codeine');
insert into treatments (name) values ('Skin Rashes Eczema');
insert into treatments (name) values ('Flumazenil');
insert into treatments (name) values ('Lisinopril');
insert into treatments (name) values ('Prandin');
insert into treatments (name) values ('Phendimetrazine Tartrate');
insert into treatments (name) values ('Free Radical');
insert into treatments (name) values ('VANILLA CREAM AND APPLE BLOSSOM ANTIBACTERIAL HAND SANITIZER');
insert into treatments (name) values ('UV Capture Water Zero Sunspray');
insert into treatments (name) values ('Staphysagria Kit Refill');
insert into treatments (name) values ('BioTox Lyme');
insert into treatments (name) values ('Flecainide Acetate');
insert into treatments (name) values ('Promethazine Hydrochloride');
insert into treatments (name) values ('Healthy Accents ibuprofen');
insert into treatments (name) values ('RAY DOL');
insert into treatments (name) values ('Lorazepam');
insert into treatments (name) values ('Lynx Antibacterial');
insert into treatments (name) values ('Oleptro');
insert into treatments (name) values ('clotrimazole');
insert into treatments (name) values ('Temozolomide');
insert into treatments (name) values ('AMBROSIA TRIFIDA POLLEN');
insert into treatments (name) values ('Ibuprofen');
insert into treatments (name) values ('Bacteria Plus');
insert into treatments (name) values ('montelukast sodium');
insert into treatments (name) values ('Secret Outlast and Olay Smooth');
insert into treatments (name) values ('Neo');
insert into treatments (name) values ('Pramipexole Dihydrochloride');
insert into treatments (name) values ('allergy relief d');
insert into treatments (name) values ('ASSURED NASAL RELIEF ORIGINAL');
insert into treatments (name) values ('Degree');
insert into treatments (name) values ('Bupivacaine Hydrochloride');
insert into treatments (name) values ('cough and chest congestion');
insert into treatments (name) values ('Labor Exhaustion');
insert into treatments (name) values ('Sodium Fluoride F 18');
insert into treatments (name) values ('Oxygen Helium Mixture 30/70');
insert into treatments (name) values ('Miracet');
insert into treatments (name) values ('Extra Strength Pain Relief');
insert into treatments (name) values ('cold and allergy relief');
insert into treatments (name) values ('Paprika');
insert into treatments (name) values ('Lisinopril');
insert into treatments (name) values ('ibuprofen');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('Care One migraine relief');
insert into treatments (name) values ('povidine iodine');
insert into treatments (name) values ('Atropine Sulfate');
insert into treatments (name) values ('Acnotex acne Treatment');
insert into treatments (name) values ('Nettle');
insert into treatments (name) values ('Servo-Stat TE');
insert into treatments (name) values ('Lisinopril and Hydrochlorothiazide');
insert into treatments (name) values ('Ceftriaxone Sodium');
insert into treatments (name) values ('BABOR BODY LINE THERMAL Firming Body');
insert into treatments (name) values ('Fruit Medley Antibacterial Foaming Hand Wash');
insert into treatments (name) values ('MINERALIZE');
insert into treatments (name) values ('Norgestimate and Ethinyl Estradiol');
insert into treatments (name) values ('HEB');
insert into treatments (name) values ('Oxygen');
insert into treatments (name) values ('ANTIBACTERIAL FOAMING');
insert into treatments (name) values ('Propofol');
insert into treatments (name) values ('Laura Lynn Anticavity Whitening plus Mouthwash');
insert into treatments (name) values ('APRIL Bath and Shower Warm Vanilla Sugar Scented Antibacterial HAND SANITIZER');
insert into treatments (name) values ('Lexapro');
insert into treatments (name) values ('Nifedical');
insert into treatments (name) values ('Cauliflower');
insert into treatments (name) values ('PODOFILOX');
insert into treatments (name) values ('HGH Vitality');
insert into treatments (name) values ('ZALEPLON');
insert into treatments (name) values ('simply right diphenhydramine hydrochloride');
insert into treatments (name) values ('CVS Redness Relief Maximum');
insert into treatments (name) values ('ibuprofen');
insert into treatments (name) values ('EMEND');
insert into treatments (name) values ('triamcinolone acetonide');
insert into treatments (name) values ('Sarna');
insert into treatments (name) values ('Sotalol Hydrochloride');
insert into treatments (name) values ('Kinesys');
insert into treatments (name) values ('rx act ibuprofen pm');
insert into treatments (name) values ('ESIKA');
insert into treatments (name) values ('Multi Vitamin and Mineral');
insert into treatments (name) values ('Fluconazole');
insert into treatments (name) values ('Lisinopril and hydrochlorothiazide');
insert into treatments (name) values ('Femmesil Creme');
insert into treatments (name) values ('Male Complex');
insert into treatments (name) values ('Hydrating Lip Balm SPF 15 sunscreen');
insert into treatments (name) values ('Amoxicillin');
insert into treatments (name) values ('JIANZE ALCOHOL PREP PAD LARGE');
insert into treatments (name) values ('good sense all day pain relief');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('Cheongin Haejanghwan');
insert into treatments (name) values ('FOAMING HAND SANITIZER');
insert into treatments (name) values ('Betamethasone Valerate');
insert into treatments (name) values ('Rite Aid Cold Sore Treatment');
insert into treatments (name) values ('Basil and Plum Antibacterial Foaming Hand Wash');
insert into treatments (name) values ('Cough Perspiration');
insert into treatments (name) values ('PureLife APF');
insert into treatments (name) values ('Hydroxyzine Hydrochloride');
insert into treatments (name) values ('Mentholatum Ironman');
insert into treatments (name) values ('Renagel');
insert into treatments (name) values ('Emtriva');
insert into treatments (name) values ('PredniSONE');
insert into treatments (name) values ('Exuviance CoverBlend Skin Caring Foundation');
insert into treatments (name) values ('Feelin Fresh Original');
insert into treatments (name) values ('Isoniazid');
insert into treatments (name) values ('Food - Plant Source, Carrot Daucus carota');
insert into treatments (name) values ('SELZENTRY');
insert into treatments (name) values ('Renes Carbo Special Order');
insert into treatments (name) values ('Ritalin');
insert into treatments (name) values ('APRIL Bath and Shower Warm Vanilla Sugar Scented Antibacterial HAND SANITIZER');
insert into treatments (name) values ('UP and UP');
insert into treatments (name) values ('Bupropion Hydrochloride');
insert into treatments (name) values ('SEROQUEL');
insert into treatments (name) values ('pain relief');
insert into treatments (name) values ('Diabetigen');
insert into treatments (name) values ('BETHANECHOL CHLORIDE');
insert into treatments (name) values ('PYtest');
insert into treatments (name) values ('COLGATE KIDS');
insert into treatments (name) values ('Dobutamine Hydrochloride');
insert into treatments (name) values ('MOIST MOISTURE EMULSION');
insert into treatments (name) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into treatments (name) values ('Holiday EleganceFrosted Gingerbre');
insert into treatments (name) values ('Amlodipine Besylate and Benazepril Hydrochloride');
insert into treatments (name) values ('Cultivated Rye');
insert into treatments (name) values ('Quality Petroleum Aloe Vera');
insert into treatments (name) values ('Estradiol');
insert into treatments (name) values ('PreferaOB One');
insert into treatments (name) values ('Povidone-Iodine');
insert into treatments (name) values ('ASPERGILLUS TERREUS');
insert into treatments (name) values ('Smooth Brome');
insert into treatments (name) values ('Giant Wild Rye');
insert into treatments (name) values ('Indomethacin');
insert into treatments (name) values ('Food - Plant Source, Brazil Nut Bertholletia excelsa');
insert into treatments (name) values ('Sodium Phosphates');
insert into treatments (name) values ('Aspir Low');
insert into treatments (name) values ('Topiramate');
insert into treatments (name) values ('Extra Strength Pain Reliever PM');
insert into treatments (name) values ('Daisy Blossom Antibacterial Hand Sanitizer');
insert into treatments (name) values ('Ondansetron');
insert into treatments (name) values ('Oxybutynin Chloride');
insert into treatments (name) values ('OXYGEN');
insert into treatments (name) values ('AQUAFRESH');
insert into treatments (name) values ('Aire-Master');
insert into treatments (name) values ('TEMAZEPAM');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('Sore Throat headache');
insert into treatments (name) values ('Medium Expert Finish Makeup Makeup Broad Spectrum SPF 25');
insert into treatments (name) values ('Pantoprazole Sodium');
insert into treatments (name) values ('Verapamil Hydrochloride');
insert into treatments (name) values ('Molds, Rusts and Smuts, Mucor racemosus');
insert into treatments (name) values ('Black Walnut');
insert into treatments (name) values ('AlbuRx');
insert into treatments (name) values ('BENZTROPINE MESYLATE');
insert into treatments (name) values ('Buspirone Hydrochloride');
insert into treatments (name) values ('Buxom Show Some Skin Weightless Foundation Broad Spectrum SPF 30');
insert into treatments (name) values ('Levetiracetam');
insert into treatments (name) values ('Lactulose');
insert into treatments (name) values ('DebMed Antimicrobial');
insert into treatments (name) values ('Glycopyrrolate');
insert into treatments (name) values ('Oxygen-Nitrogen Mixture');
insert into treatments (name) values ('Eastern Cottonwood');
insert into treatments (name) values ('Ipratropium Bromide and Albuterol Sulfate');
insert into treatments (name) values ('Metoprolol Tartrate');
insert into treatments (name) values ('Eye Wash');
insert into treatments (name) values ('medroxyprogesterone acetate');
insert into treatments (name) values ('Sunmark antacid');
insert into treatments (name) values ('Spearmint');
insert into treatments (name) values ('BEEVENOM ESSENCE');
insert into treatments (name) values ('Clotrimazole');
insert into treatments (name) values ('Fluticasone Propionate');
insert into treatments (name) values ('Magnevist');
insert into treatments (name) values ('DentiCare Denti-Pro');
insert into treatments (name) values ('Pentazocine and naloxone');
insert into treatments (name) values ('Proctofoam');
insert into treatments (name) values ('Anzemet');
insert into treatments (name) values ('Treatment Set TS350394');
insert into treatments (name) values ('Carvedilol');
insert into treatments (name) values ('GAS RELIEF');
insert into treatments (name) values ('Erythromycin');
insert into treatments (name) values ('Sterile Water');
insert into treatments (name) values ('Cotton Candy');
insert into treatments (name) values ('Tivorbex');
insert into treatments (name) values ('Medrol');
insert into treatments (name) values ('Aveeno Active Naturals Positively Radiant Daily Moisturizer');
insert into treatments (name) values ('Misoprostol');
insert into treatments (name) values ('Kadian');
insert into treatments (name) values ('Quinidine Gluconate');
insert into treatments (name) values ('Cyclosporine');
insert into treatments (name) values ('Harmon Face Values Medicated');
insert into treatments (name) values ('good neighbor pharmacy anti diarrheal');
insert into treatments (name) values ('BareMinerals');
insert into treatments (name) values ('Lice Treatment');
insert into treatments (name) values ('Piroxicam');
insert into treatments (name) values ('Alprazolam');
insert into treatments (name) values ('Aphedrid Cold and Allergy');
insert into treatments (name) values ('Strattera');
insert into treatments (name) values ('Miconazole Nitrate');
insert into treatments (name) values ('Hives');
insert into treatments (name) values ('Allopurinol');
insert into treatments (name) values ('Depo-Testosterone');
insert into treatments (name) values ('Pramipexole Dihydrochloride');
insert into treatments (name) values ('Clorox CareConcepts Bed Bath and Hygiene');
insert into treatments (name) values ('Couch Quack Grass');
insert into treatments (name) values ('Nitrofurantoin (macrocrystals)');
insert into treatments (name) values ('Junior Aspirin Free Rapid Tabs');
insert into treatments (name) values ('Gas-X');
insert into treatments (name) values ('BIOSOLIS Sun Milk UVA Sunscreen Face and Body Broad Spectrum SPF50 KIDS');
insert into treatments (name) values ('MINERAL CONCEALER');
insert into treatments (name) values ('Lymphdrainex');
insert into treatments (name) values ('ibuprofen');
insert into treatments (name) values ('TURKEY FOOD');
insert into treatments (name) values ('DG BODY');
insert into treatments (name) values ('Adult Tussin Cough Gels');
insert into treatments (name) values ('METOPROLOL SUCCINATE');
insert into treatments (name) values ('Vitamin A D');
insert into treatments (name) values ('good sense antacid');
insert into treatments (name) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into treatments (name) values ('Mixture of Standardized and Non-Standardized Southern Grasses');
insert into treatments (name) values ('METOPROLOL TARTRATE');
insert into treatments (name) values ('LACHESIS MUTUS');
insert into treatments (name) values ('Childrens Pain and Fever Acetaminophen');
insert into treatments (name) values ('diltiazem hydrochloride');
insert into treatments (name) values ('AZITHROMYCIN');
insert into treatments (name) values ('Atenolol');
insert into treatments (name) values ('sodium sulfacetamide 10 and sulfur 5');
insert into treatments (name) values ('Citrus Basil Antibacterial Hand Wash');
insert into treatments (name) values ('By Pharmicell Lab Luxury Cell Performance Serum');
insert into treatments (name) values ('LivTac');
insert into treatments (name) values ('Low Dose Chewable Aspirin');
insert into treatments (name) values ('SAFEWAY');
insert into treatments (name) values ('BUNAVAIL');
insert into treatments (name) values ('NITRO-DUR');
insert into treatments (name) values ('ibuprofen');
insert into treatments (name) values ('Moore Medical Cherry Cough Suppressant/Anesthetic Drops');
insert into treatments (name) values ('Lidocaine Hydrochloride');
insert into treatments (name) values ('Herbion Naturals Honey Lemon');
insert into treatments (name) values ('Warfarin Sodium');
insert into treatments (name) values ('soCALM Pain Relieving');
insert into treatments (name) values ('Atenolol');
insert into treatments (name) values ('Escitalopram');
insert into treatments (name) values ('GermFree24 Health-care Personnel Handwash');
insert into treatments (name) values ('Metoprolol Tartrate');
insert into treatments (name) values ('Nitrous Oxide');
insert into treatments (name) values ('Conjunctiva Argentum Special Order');
insert into treatments (name) values ('Torisel');
insert into treatments (name) values ('Sofskin Baby');
insert into treatments (name) values ('CALC FLUOR');
insert into treatments (name) values ('Strattera');
insert into treatments (name) values ('Olanzapine and Fluoxetine');
insert into treatments (name) values ('Allergy Relief');
insert into treatments (name) values ('TrophAmine');
insert into treatments (name) values ('Fluconazole');
insert into treatments (name) values ('Bio Vervain');
insert into treatments (name) values ('Short/Giant Ragweed Mixture');
insert into treatments (name) values ('Antioxidant Daily Protectant SPF 30');
insert into treatments (name) values ('SYNTHROID');
insert into treatments (name) values ('Ipratropium Bromide');
insert into treatments (name) values ('Glytone acne cleansing toner');
insert into treatments (name) values ('Rompe Pecho');
insert into treatments (name) values ('PREMIUM HAND SANITIZER');
insert into treatments (name) values ('CHEM HP');
insert into treatments (name) values ('Zenzedi');
insert into treatments (name) values ('Levothyroxine Sodium');
insert into treatments (name) values ('LISINOPRIL');
insert into treatments (name) values ('Fig');
insert into treatments (name) values ('Povidone Iodine Impregnated');
insert into treatments (name) values ('Fluoxetine');
insert into treatments (name) values ('tussin dm');
insert into treatments (name) values ('Sibling Jealousy');
insert into treatments (name) values ('Real Deal Foundation');
insert into treatments (name) values ('RODAN FIELDS SOOTHE 4 Mineral Sunscreen BROAD SPECTRUM SPF 30');
insert into treatments (name) values ('PROGESTERONE');
insert into treatments (name) values ('Poppyseed');
insert into treatments (name) values ('Hydroxyzine Hydrochloride');
insert into treatments (name) values ('Body Series Invisible Solid Deodorant and Antiperspirant');
insert into treatments (name) values ('Torsemide');
insert into treatments (name) values ('ConRx');
insert into treatments (name) values ('GLIPIZIDE');
insert into treatments (name) values ('Lisinopril');
insert into treatments (name) values ('Verapamil Hydrochloride');
insert into treatments (name) values ('Fosinopril Sodium and Hydrochlorothiazide');
insert into treatments (name) values ('Lisinopril');
insert into treatments (name) values ('Clindamycin Phosphate');
insert into treatments (name) values ('ROSACEA');
insert into treatments (name) values ('Oxygen');
insert into treatments (name) values ('Up and Up Anticavity Toothpaste Whitening');
insert into treatments (name) values ('Thyrogen');
insert into treatments (name) values ('CARMEX original lip balm EXTERNAL ANALGESIC');
insert into treatments (name) values ('Folic Acid');
insert into treatments (name) values ('EpiCare Antimicrobial Lotion Soap');
insert into treatments (name) values ('Diltiazem Hydrochloride');
insert into treatments (name) values ('SIRTURO');
insert into treatments (name) values ('Tigan');
insert into treatments (name) values ('Torsemide');
insert into treatments (name) values ('RISPERDAL');
insert into treatments (name) values ('Venlafaxine Hydrochloride');
insert into treatments (name) values ('Alcohol Prep Pad');
insert into treatments (name) values ('Burnaid Burn Gel');
insert into treatments (name) values ('Ritussin Expectorant');
insert into treatments (name) values ('Promolaxin');
insert into treatments (name) values ('Hydroxyzine Hydrochloride');
insert into treatments (name) values ('Etodolac');
insert into treatments (name) values ('Ketoprofen');
insert into treatments (name) values ('potassium chloride');
insert into treatments (name) values ('ibuprofen pm');
insert into treatments (name) values ('EPICOCCUM NIGRUM');
insert into treatments (name) values ('GEODON');
insert into treatments (name) values ('Daytime Cold and Flu Relief');
insert into treatments (name) values ('SUN Solar Defense Oil-free SPF 30');
insert into treatments (name) values ('TOTAL FEM-BAL');
insert into treatments (name) values ('Endopar');
insert into treatments (name) values ('LAMICTAL');
insert into treatments (name) values ('Mugwort Sage Pollen');
insert into treatments (name) values ('CLE DE PEAU BEAUTE GENTLE PROTECTIVE I');
insert into treatments (name) values ('Illusion Tinted Moisturizer Broad Spectrum Beige');
insert into treatments (name) values ('Pleo Form');
insert into treatments (name) values ('Minocycline hydrochloride');
insert into treatments (name) values ('Help I have allergies');
insert into treatments (name) values ('Lexapro');
insert into treatments (name) values ('Fentanyl Citrate');
insert into treatments (name) values ('leader childrens pain and fever');
insert into treatments (name) values ('ELAPRASE');
insert into treatments (name) values ('HYDROMORPHONE HYDROCHLORIDE');
insert into treatments (name) values ('Junel 1.5/30');
insert into treatments (name) values ('Promethazine Hydrochloride');
insert into treatments (name) values ('Lombardy Poplar');
insert into treatments (name) values ('Kimvent Q2 oral care kit');
insert into treatments (name) values ('Lil Drug Store Nighttime Sleep-Aid');
insert into treatments (name) values ('Timoptic');
insert into treatments (name) values ('CONSTIPATION');
insert into treatments (name) values ('Wash-Up Towelette');
insert into treatments (name) values ('Gold Bond Ultimate Eczema Relief');
insert into treatments (name) values ('Common Sagebrush');
insert into treatments (name) values ('Health Mart z-sleep');
insert into treatments (name) values ('MBM 5 Large Intestine');
insert into treatments (name) values ('Oxaliplatin');
insert into treatments (name) values ('Hemorrhoid Complex');
insert into treatments (name) values ('flormar CC Magical Color Effect Color Correcting Cream Sunscreen Broad Spectrum SPF 15 CC02');
insert into treatments (name) values ('Nitroglycerin');
insert into treatments (name) values ('Pravastatin Sodium');
insert into treatments (name) values ('TRICITRATES');
insert into treatments (name) values ('OXYGEN');
insert into treatments (name) values ('Hydrocodone Bitartrate and Acetaminophen');
insert into treatments (name) values ('cetirizine hydrochloride');
insert into treatments (name) values ('Beyond BB Perfecting Foundation Broad Spectrum SPF 15 Sunscreen');
insert into treatments (name) values ('Diltiazem Hydrochloride');
insert into treatments (name) values ('Colgate Sensitive Pro Relief Whitening');
insert into treatments (name) values ('Furosemide');
insert into treatments (name) values ('STAVZOR');
insert into treatments (name) values ('Antispetic');
insert into treatments (name) values ('Molds, Rusts and Smuts, Fusarium vasinfectum');
insert into treatments (name) values ('Imipramine Hydrochloride');
insert into treatments (name) values ('Naproxen');
insert into treatments (name) values ('Hexalen');
insert into treatments (name) values ('CALCAREA CARBONICA');
insert into treatments (name) values ('Nighttime Sleep Aid');
insert into treatments (name) values ('Credit Card Shape Hand Sanitizer');
insert into treatments (name) values ('Maalox');
insert into treatments (name) values ('Petrochemical Detox');
insert into treatments (name) values ('Hydroxyzine Hydrochloride');
insert into treatments (name) values ('Hydrocodone Bitartrate And Acetaminophen');
insert into treatments (name) values ('Caverject Impulse');
insert into treatments (name) values ('Pepper Tree Pollen');
insert into treatments (name) values ('ARIZONA CYPRESS POLLEN');
