insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Raspberries - Frozen', 7);
insert into ingredients (name_food, name_inv, amount) values ('Salcedo pizza', 'Red Currant Jelly', 4);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', 'Tray - 12in Rnd Blk', 2);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'Whmis - Spray Bottle Trigger', 10);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Chives - Fresh', 5);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', ' Pieces', 7);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', 'Wine - Magnotta - Cab Sauv', 5);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', ' Pieces', 3);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', ' Whole', 3);
insert into ingredients (name_food, name_inv, amount) values ('Banovo Polje pizza', 'Syrup - Monin - Blue Curacao', 1);
insert into ingredients (name_food, name_inv, amount) values ('Babakankadu pizza', 'Wine - Magnotta - Cab Sauv', 3);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Syrup - Monin - Blue Curacao', 10);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Coke - Classic', 7);
insert into ingredients (name_food, name_inv, amount) values ('Banovo Polje pizza', 'pizza dough', 9);
insert into ingredients (name_food, name_inv, amount) values ('Grand Forks pizza', 'Wine - Magnotta - Cab Sauv', 6);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Basil - Primerba', 2);
insert into ingredients (name_food, name_inv, amount) values ('Binjiang pizza', 'cheese', 7);
insert into ingredients (name_food, name_inv, amount) values ('Troitsk pizza', 'Steam Pan Full Lid', 6);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Coke - Classic', 2);
insert into ingredients (name_food, name_inv, amount) values ('Karítsa pizza', 'Yucca', 9);
insert into ingredients (name_food, name_inv, amount) values ('Karítsa pizza', 'Syrup - Monin - Blue Curacao', 6);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', ' Fresh', 6);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Cake - Bande Of Fruit', 8);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'cheese', 6);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', 'Yucca', 2);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Yucca', 2);
insert into ingredients (name_food, name_inv, amount) values ('Salcedo pizza', 'Red Currant Jelly', 3);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Syrup - Monin - Blue Curacao', 10);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'cheese', 6);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', 'cheese', 4);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'Extract - Raspberry', 8);
insert into ingredients (name_food, name_inv, amount) values ('Banovo Polje pizza', 'Nut - Pecan', 7);
insert into ingredients (name_food, name_inv, amount) values ('San Francisco de la Paz pizza', 'Syrup - Monin - Blue Curacao', 4);
insert into ingredients (name_food, name_inv, amount) values ('Babakankadu pizza', 'Island Oasis - Cappucino Mix', 9);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', 'Whmis - Spray Bottle Trigger', 4);
insert into ingredients (name_food, name_inv, amount) values ('Babakankadu pizza', ' Shelled', 6);
insert into ingredients (name_food, name_inv, amount) values ('Troitsk pizza', 'Chives - Fresh', 3);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', ' Shelled', 5);
insert into ingredients (name_food, name_inv, amount) values ('San Francisco de la Paz pizza', 'Sole - Dover', 2);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'Raspberries - Frozen', 4);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', 'Wine - Magnotta - Cab Sauv', 10);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', 'Chives - Fresh', 10);
insert into ingredients (name_food, name_inv, amount) values ('Banovo Polje pizza', 'Basil - Primerba', 3);
insert into ingredients (name_food, name_inv, amount) values ('Salcedo pizza', ' Pieces', 9);
insert into ingredients (name_food, name_inv, amount) values ('Wonosobo pizza', 'Chives - Fresh', 9);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', 'Raspberries - Frozen', 2);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', ' Whole', 1);
insert into ingredients (name_food, name_inv, amount) values ('Binjiang pizza', 'flour', 2);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Nut - Pecan', 9);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Sole - Dover', 7);
insert into ingredients (name_food, name_inv, amount) values ('Wonosobo pizza', 'Muffin - Bran Ind Wrpd', 5);
insert into ingredients (name_food, name_inv, amount) values ('San Francisco de la Paz pizza', 'Cake - Bande Of Fruit', 4);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Island Oasis - Cappucino Mix', 5);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Beef - Montreal Smoked Brisket', 1);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', 'Nut - Pecan', 7);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', ' Fresh', 3);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'Shrimp - Prawn', 4);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', 'Yucca', 8);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', 'Island Oasis - Cappucino Mix', 10);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Yucca', 7);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', 'Nut - Pistachio', 3);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', 'tomato sauce', 2);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'Bandage - Fexible 1x3', 9);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Tray - 12in Rnd Blk', 4);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Sole - Dover', 1);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', ' 355 Ml', 9);
insert into ingredients (name_food, name_inv, amount) values ('Wonosobo pizza', 'Coke - Classic', 2);
insert into ingredients (name_food, name_inv, amount) values ('Karítsa pizza', ' Fresh', 2);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Bandage - Fexible 1x3', 7);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Lamb - Whole Head Off', 5);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Pork - European Side Bacon', 7);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', 'flour', 5);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Basil - Primerba', 5);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', 'Whmis - Spray Bottle Trigger', 10);
insert into ingredients (name_food, name_inv, amount) values ('Binjiang pizza', 'Syrup - Monin - Blue Curacao', 7);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Coke - Classic', 5);
insert into ingredients (name_food, name_inv, amount) values ('Wonosobo pizza', 'Yucca', 8);
insert into ingredients (name_food, name_inv, amount) values ('Roissy Charles-de-Gaulle pizza', 'Bandage - Fexible 1x3', 8);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'Coke - Classic', 4);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Island Oasis - Cappucino Mix', 8);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', ' Paste', 4);
insert into ingredients (name_food, name_inv, amount) values ('Roissy Charles-de-Gaulle pizza', 'pizza dough', 1);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Turkey Leg With Drum And Thigh', 9);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Chives - Fresh', 4);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', ' 355 Ml', 2);
insert into ingredients (name_food, name_inv, amount) values ('Troitsk pizza', 'Red Currant Jelly', 10);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', 'Coke - Classic', 2);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Turkey Leg With Drum And Thigh', 7);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Tray - 12in Rnd Blk', 6);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', 'Beef - Montreal Smoked Brisket', 9);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'Coke - Classic', 2);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', 'Beef - Montreal Smoked Brisket', 2);
insert into ingredients (name_food, name_inv, amount) values ('San Francisco de la Paz pizza', 'Tray - 12in Rnd Blk', 5);
insert into ingredients (name_food, name_inv, amount) values ('Babakankadu pizza', 'Turkey Leg With Drum And Thigh', 2);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Nut - Pecan', 5);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', 'Chives - Fresh', 4);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Extract - Raspberry', 9);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Muffin - Bran Ind Wrpd', 3);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'tomato sauce', 2);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Nut - Pecan', 4);
insert into ingredients (name_food, name_inv, amount) values ('Bombon pizza', 'Lamb - Whole Head Off', 8);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', ' Paste', 4);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Chives - Fresh', 6);
insert into ingredients (name_food, name_inv, amount) values ('Karítsa pizza', ' Shelled', 5);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'cheese', 9);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Sole - Dover', 10);
insert into ingredients (name_food, name_inv, amount) values ('Hodošan pizza', 'Chives - Fresh', 6);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Basil - Primerba', 8);
insert into ingredients (name_food, name_inv, amount) values ('Grand Forks pizza', 'Coke - Classic', 3);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', 'Shrimp - Prawn', 1);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', ' Fresh', 6);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', 'Nut - Pistachio', 6);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', ' 355 Ml', 6);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Yucca', 9);
insert into ingredients (name_food, name_inv, amount) values ('Karítsa pizza', 'Lamb - Whole Head Off', 10);
insert into ingredients (name_food, name_inv, amount) values ('San Marcelino pizza', ' Paste', 8);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Syrup - Monin - Blue Curacao', 6);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Coke - Classic', 5);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', 'cheese', 6);
insert into ingredients (name_food, name_inv, amount) values ('Babakankadu pizza', ' Shelled', 5);
insert into ingredients (name_food, name_inv, amount) values ('Rognedino pizza', ' 355 Ml', 6);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Bandage - Fexible 1x3', 5);
insert into ingredients (name_food, name_inv, amount) values ('Grand Forks pizza', 'flour', 7);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Wine - Peller Estates Late', 2);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', 'Tray - 12in Rnd Blk', 2);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Sole - Dover', 6);
insert into ingredients (name_food, name_inv, amount) values ('Salcedo pizza', 'Yucca', 6);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', 'Muffin - Bran Ind Wrpd', 2);
insert into ingredients (name_food, name_inv, amount) values ('Ambovombe pizza', 'Cake - Bande Of Fruit', 2);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', 'Syrup - Monin - Blue Curacao', 2);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', ' Paste', 6);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', 'Nut - Pecan', 9);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'Shrimp - Prawn', 10);
insert into ingredients (name_food, name_inv, amount) values ('Troitsk pizza', 'tomato sauce', 5);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'Nut - Pecan', 3);
insert into ingredients (name_food, name_inv, amount) values ('Kyjov pizza', ' Pieces', 6);
insert into ingredients (name_food, name_inv, amount) values ('Karangori pizza', 'Coke - Classic', 4);
insert into ingredients (name_food, name_inv, amount) values ('Dhali pizza', 'Bandage - Fexible 1x3', 8);
insert into ingredients (name_food, name_inv, amount) values ('Roissy Charles-de-Gaulle pizza', 'Wine - Magnotta - Cab Sauv', 1);
insert into ingredients (name_food, name_inv, amount) values ('San Francisco de la Paz pizza', 'Extract - Raspberry', 6);
insert into ingredients (name_food, name_inv, amount) values ('Union pizza', ' Shelled', 1);
insert into ingredients (name_food, name_inv, amount) values ('Šumice pizza', 'Muffin - Bran Ind Wrpd', 6);
insert into ingredients (name_food, name_inv, amount) values ('Roissy Charles-de-Gaulle pizza', 'Beef - Montreal Smoked Brisket', 5);
insert into ingredients (name_food, name_inv, amount) values ('Grand Forks pizza', 'Red Currant Jelly', 7);
insert into ingredients (name_food, name_inv, amount) values ('Troitsk pizza', 'cheese', 2);
insert into ingredients (name_food, name_inv, amount) values ('Potštát pizza', 'Sole - Dover', 4);
insert into ingredients (name_food, name_inv, amount) values ('Binjiang pizza', 'Whmis - Spray Bottle Trigger', 9);
insert into ingredients (name_food, name_inv, amount) values ('Srbinovo pizza', 'Muffin - Bran Ind Wrpd', 4);
insert into ingredients (name_food, name_inv, amount) values ('Ust’-Kachka pizza', 'cheese', 6);
insert into ingredients (name_food, name_inv, amount) values ('Cereté pizza', ' Paste', 8);
