version: '2'
volumes:
  redisdata-master:
  redisdata-slave:
services:
  nosql-redis-master:
    build: .
    image: "nosql-redis-master"
    container_name: "nosql-redis-master"
    hostname: "nosql-redis-master"
    tty: true
    volumes:
      - redisdata-master:/data
      - ../../../labs:/app/redis/labs
      - ../../../projects:/app/redis/projects
      - ../examples:/app/redis/examples
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379
    networks:
      - redis-replication
  nosql-redis-slave:
    build: .
    image: "nosql-redis-slave"
    container_name: "nosql-redis-slave"
    hostname: "nosql-redis-slave"
    tty: true
    volumes:
      - redisdata-slave:/data
      - ../../labs:/app/redis/labs
      - ../../projects:/app/redis/projects
      - ../examples:/app/redis/examples
    ports:
      - 6380:6380
    command: redis-server /usr/local/etc/redis/redis.conf --port 6380 --slaveof nosql-redis-master 6379
    networks:
      - redis-replication
networks:
  redis-replication:
