version: '2'
volumes:
  neo4j-ent-data1:
  neo4j-ent-data2:
  neo4j-ent-data3:
services:
  nosql-neo4j-ent1:
    build: .
    image: "nosql-neo4j-ent1"
    container_name: "nosql-neo4j-ent1"
    hostname: "nosql-neo4j-ent1"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_causalClustering_discoveryAdvertisedAddress=nosql-neo4j-ent1:5000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=nosql-neo4j-ent1:5000,nosql-neo4j-ent2:5000,nosql-neo4j-ent3:5000
      - NEO4J_causalClustering_raftAdvertisedAddress=nosql-neo4j-ent1:7000
      - NEO4J_causalClustering_transactionAdvertisedAddress=nosql-neo4j-ent1:6000
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connectors_default__advertised__address=nosql-neo4j-ent1
      - NEO4J_dbms_mode=CORE
    volumes:
      - neo4j-ent-data1:/data
      - ../../labs:/app/neo4j/labs
      - ../../projects:/app/neo4j/projects
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    networks:
      - neo4j-ha
  nosql-neo4j-ent2:
    build: .
    image: "nosql-neo4j-ent2"
    container_name: "nosql-neo4j-ent2"
    hostname: "nosql-neo4j-ent2"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_causalClustering_discoveryAdvertisedAddress=nosql-neo4j-ent2:5000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=nosql-neo4j-ent1:5000,nosql-neo4j-ent2:5000,nosql-neo4j-ent3:5000
      - NEO4J_causalClustering_raftAdvertisedAddress=nosql-neo4j-ent2:7000
      - NEO4J_causalClustering_transactionAdvertisedAddress=nosql-neo4j-ent2:6000
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connectors_default__advertised__address=nosql-neo4j-ent2
      - NEO4J_dbms_mode=CORE
    volumes:
      - neo4j-ent-data2:/data
      - ../../../labs:/app/neo4j/labs
      - ../../../projects:/app/neo4j/projects
    ports:
      - 7475:7474
      - 6478:6477
      - 7688:7687
    networks:
      - neo4j-ha
  nosql-neo4j-ent3:
    build: .
    image: "nosql-neo4j-ent3"
    container_name: "nosql-neo4j-ent3"
    hostname: "nosql-neo4j-ent3"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
      - NEO4J_causalClustering_discoveryAdvertisedAddress=nosql-neo4j-ent3:5000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=nosql-neo4j-ent1:5000,nosql-neo4j-ent2:5000,nosql-neo4j-ent3:5000
      - NEO4J_causalClustering_raftAdvertisedAddress=nosql-neo4j-ent3:7000
      - NEO4J_causalClustering_transactionAdvertisedAddress=nosql-neo4j-ent3:6000
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connectors_default__advertised__address=nosql-neo4j-ent3
      - NEO4J_dbms_mode=CORE
    volumes:
      - neo4j-ent-data3:/data
      - ../../labs:/app/neo4j/labs
      - ../../projects:/app/neo4j/projects
    ports:
      - 7476:7474
      - 6479:6477
      - 7689:7687
    networks:
      - neo4j-ha
networks:
  neo4j-ha:
